// Noble Lions — interactivity

// ── Language Toggle ─────────────────────────────────────────────
const translations = {
  en: {
    heroTitle:    "Building Peace Through <span class='highlight'>Cultural Understanding</span>",
    heroSubtitle: "Developing new ideas in a modern world to foster peace and stronger relationships between different cultures, communities and nations.",
    pillar1Title: "Peace & Dialogue",
    pillar1Text:  "Creating spaces for open conversation across cultural, ethnic, and national boundaries to build mutual understanding.",
    pillar2Title: "Justice & Equality",
    pillar2Text:  "Upholding civil rights, rule of law, and equal dignity for every person regardless of their origin or belief.",
    pillar3Title: "Cultural Exchange",
    pillar3Text:  "Celebrating diversity through art, language, tradition, and shared human experiences that connect us all.",
    pillar4Title: "Resilience & Growth",
    pillar4Text:  "Self-confidence isn't freedom from failure — it's the strength to rise again and reach new heights.",
    sectionCultures: "World Cultures",
    sectionCulturesDesc: "Every culture carries wisdom. Together we are stronger.",
    sectionJustice: "Justice & Rights",
    sectionJusticeDesc: "Fairness is the foundation of lasting peace between peoples.",
    joinTitle: "Join the Movement",
    joinDesc: "Be part of a global community committed to peace, understanding, and cross-cultural friendship.",
    sectionFaith: "Walking with the Creator",
    sectionFaithDesc: "Every step of our journey should be grounded in the Creator.",
    faithVerse1: "Every step of our journey should be grounded in the Creator.",
    faithVerse2: "Because a path and life journey without the Creator is difficult and impossible.",
    faithVerse3: "Therefore, for our success and well-being, we should walk with the Creator.",
    // Self-Reliance section
    sectionReliance: "Existence in Self-Reliance",
    sectionRelianceDesc: "What conditions enable a person to live with true independence and inner strength?",
    relianceLead: "Self-reliance is not isolation. It is the freedom that comes when a person is rooted in faith, equipped with knowledge, strengthened by community, and protected by justice — able to stand, choose, and contribute on their own terms.",
    reliance1Title: "Spiritual Foundation",
    reliance1Text: "Grounding life in the Creator provides clarity, courage, and a compass that guides every decision. Without this anchor, the journey of existence grows heavy and directionless.",
    reliance2Title: "Inner Strength & Resilience",
    reliance2Text: "Self-confidence is not the absence of failure — it is the certainty that you have the strength to rise again. Resilience is the core condition of a self-reliant existence.",
    reliance3Title: "Knowledge & Wisdom",
    reliance3Text: "Education and the pursuit of wisdom open doors that otherwise remain closed. A person equipped with knowledge can navigate life on their own terms and lift others along the way.",
    reliance4Title: "Community & Solidarity",
    reliance4Text: "No one achieves true self-reliance in isolation. A strong community provides the safety net and encouragement that empower every individual to stand on their own feet.",
    reliance5Title: "Justice & Equal Opportunity",
    reliance5Text: "Fair conditions in society — rule of law, equal access, and civil rights — are essential conditions that allow every person to pursue self-reliance regardless of their background.",
    developTag: "ብከመይ ምምዕባል · How to Develop",
    developTitle: "How to Develop Self-Reliance",
    developDesc: "Practical steps — each one a building block on the path to independent, purposeful living.",
    step1Title: "Root yourself in faith & spiritual clarity",
    step1Text: "Begin every day with prayer, reflection, or meditation. Let spiritual grounding be the compass that shapes your choices. When your foundation is the Creator, you gain a clarity that cannot be shaken by circumstances.",
    step2Title: "Build daily habits of self-discipline",
    step2Text: "Set clear goals and track your progress. Wake with intention, work with focus, rest with purpose. Small daily disciplines — practised consistently — compound into profound personal freedom and independence.",
    step3Title: "Commit to lifelong learning",
    step3Text: "Read, study, ask questions, and seek mentors. Knowledge is the currency of self-reliance — the more you learn, the more doors open to you. Never stop growing your mind and your skills.",
    step4Title: "Develop financial awareness & responsibility",
    step4Text: "Understand how money works, learn to save consistently, avoid unnecessary debt, and build resources step by step. Financial literacy is one of the most practical expressions of self-reliance.",
    step5Title: "Cultivate relationships that grow you",
    step5Text: "Choose friends, mentors and community who challenge you to grow, support you when you fall, and celebrate your progress. No one becomes self-reliant alone — the right people accelerate your journey.",
    step6Title: "Take full responsibility for your choices",
    step6Text: "Own your decisions and their consequences — both successes and failures. Stop attributing everything to circumstances and start responding to them. Responsibility is the heart of self-reliance.",
    step7Title: "Give back — serve your community",
    step7Text: "True self-reliance does not end with you — it overflows into service to others. When you help lift another person, your own ground grows firmer. The highest expression of independence is choosing to give.",
    relianceClosing: "Self-reliance is built step by step: through faith, discipline, learning, responsibility, and service to others.",
    // Governance section
    sectionGov: "What is Governance?",
    sectionGovDesc: "Understanding the principles and practice of governing ourselves, our communities, and our institutions.",
    govDefHeading: "ስነ ምሕደራ — The Meaning of Governance",
    govDefP1: "Governance is the system of rules, practices, processes and values by which a community, organisation, or nation directs itself — making decisions, distributing power, and fulfilling responsibilities to those it serves.",
    govDefP2: "Good governance is not just about who holds authority — it is about <em>how</em> that authority is exercised: with transparency, accountability, fairness, and in the interests of all people.",
    govP1: "Transparency", govP1Sub: "ንጽህና",
    govP2: "Accountability", govP2Sub: "ሓላፍነት",
    govP3: "Participation", govP3Sub: "ተሳትፎ",
    govP4: "Rule of Law", govP4Sub: "ልዕልና ሕጊ",
    govP5: "Effectiveness", govP5Sub: "ውጽኢታዊነት",
    govP6: "Justice", govP6Sub: "ፍትሒ",
    govHowTag: "ብከመይ ይካየድ · How It Is Conducted",
    govHowTitle: "How is Self-Governance Conducted?",
    govHowDesc: "Six essential mechanisms — from principles to practice — that enable genuine self-governance at every level: personal, community, and national.",
    govStep1Title: "Establish clear principles & shared values",
    govStep1Text: "Every system of self-governance begins with agreed values — honesty, dignity, fairness, and service. These principles act as the constitution of behaviour that binds leaders and citizens alike, providing a compass for every decision made in the collective interest.",
    govStep2Title: "Build transparent structures & clear roles",
    govStep2Text: "Good governance requires clear organisational structures — defined roles, responsibilities, and decision-making processes that everyone understands. When people know who is responsible for what and how decisions are made, trust is built and confusion is avoided.",
    govStep3Title: "Ensure accountability & oversight",
    govStep3Text: "Leaders and institutions must be answerable for their decisions and actions. Accountability systems — audits, reviews, reporting, and consequences for misconduct — are the guardrails that prevent abuse of power and keep governance honest and effective.",
    govStep4Title: "Enable broad participation & inclusion",
    govStep4Text: "Self-governance thrives when every voice has a place in decision-making. Inclusive processes — consultations, elections, open forums, and community dialogue — ensure that governance reflects the real needs and aspirations of all people, not just a privileged few.",
    govStep5Title: "Uphold the rule of law equally",
    govStep5Text: "Laws must apply equally to all people — the powerful and the powerless alike. The rule of law creates a level playing field, protects individual rights, and prevents governance from becoming the instrument of personal interest. Without it, self-governance collapses into domination.",
    govStep6Title: "Commit to continuous learning & improvement",
    govStep6Text: "No governance system is perfect from the start. The mark of good self-governance is its willingness to evaluate, learn from mistakes, and reform. Regular reviews, feedback loops, and the courage to change course are what transform adequate governance into excellent governance.",
    govClosing: "Each type of governance is measured through the culture and beliefs of its society. Good governance in any form is rooted in transparency, accountability, and justice.",
    govTypesTag: "ዝተፈላለዩ ዓይነት ምሕደራ · Types of Governance",
    govTypesTitle: "Different Types of Governance",
    govTypesDesc: "Governance takes many forms across societies — each shaped and evaluated through the lens of that society's culture, values, and beliefs.",
    govType1Badge: "ናይ ፋይናንሳዊ ምሕደራ",
    govType1Title: "Financial Governance",
    govType1Text: "Financial governance is the system of rules, processes, and structures through which resources — money, assets, and economic opportunities — are managed, allocated, and accounted for within an organisation, community, or nation.",
    govType1L1: "Budgeting & fiscal responsibility",
    govType1L2: "Transparency in spending & auditing",
    govType1L3: "Equitable distribution of resources",
    govType1L4: "Anti-corruption measures & oversight",
    govType1L5: "Long-term economic planning",
    govTypeCultureLabel: "Cultural dimension:",
    govType1Culture: "Every culture holds values around wealth, generosity, and equity. Financial governance that reflects a society's ethic of fairness and collective responsibility earns trust and sustains prosperity across generations.",
    govType2Badge: "ህዝባዊ ምሕደራ",
    govType2Title: "Public & Administrative Governance",
    govType2Text: "Public governance is the system through which governments, institutions, and civil authorities organise and deliver services, uphold rights, and manage collective affairs in the interest of all citizens — built on law, representation, and accountability.",
    govType2L1: "Democratic elections & representation",
    govType2L2: "Rule of law & constitutional order",
    govType2L3: "Delivery of public services",
    govType2L4: "Civil rights & protection of minorities",
    govType2L5: "Separation of powers & checks and balances",
    govType2Culture: "The form public governance takes is deeply shaped by a society's history, traditions, and values. What legitimises authority — election, consensus, tradition, or community elder — varies across cultures, and effective governance respects that diversity.",
    govType3Badge: "ሃይማኖታዊ ምሕደራ",
    govType3Title: "Religious Governance",
    govType3Text: "Religious governance is the way faith communities, religious institutions, and spiritual traditions organise themselves — guiding moral conduct, community practice, and the relationship between individuals, their communities, and the Creator.",
    govType3L1: "Moral & ethical codes of conduct",
    govType3L2: "Leadership structures: clergy, elders, councils",
    govType3L3: "Dispute resolution through faith traditions",
    govType3L4: "Stewardship of community and charitable giving",
    govType3L5: "Spiritual accountability before the Creator",
    govType3Culture: "In many societies, religious belief is inseparable from governance — shaping laws, family structure, community obligations, and how justice is understood. Respecting the role of faith in governance means understanding and honouring that depth of meaning.",
    govTypesNote: "<strong>Each type of governance is shaped by culture and belief.</strong> No single model fits every society. The most effective governance — financial, public, or religious — grows from the authentic values of the people it serves, earning legitimacy not by imposition but by alignment with what that community holds most sacred and true.",
    // Cultural Heritage & Generational Duty
    sectionHeritage: "Our Cultural Heritage &amp; Generational Duty",
    sectionHeritageDesc: "The existence of our society must be confirmed through action — preserving our culture and history, educating the next generation, and preparing them to stand with the world.",
    heritageDecl: "It is our duty to confirm the existence of our society through practice — in every area of our lives. Our highest priority is to return our culture and history, civilised and advanced through education, to its proper place. We must train the next generation in the correct methods of our culture and equip them with educated, civilised learning so that they can compete with the world.",
    hCard1Badge: "ባህልናን ታሪኽናን",
    hCard1Title: "Culture &amp; History",
    hCard1Text: "Our culture and history are the foundation of who we are. They carry the wisdom, values, and identity passed down through generations — a living inheritance that must be understood, honoured, and taught anew in every era.",
    hCard1L1: "Preserve oral traditions, literature, and language",
    hCard1L2: "Document and teach our historical narrative",
    hCard1L3: "Honour the values embedded in cultural practice",
    hCard1L4: "Return culture to its proper, civilised expression",
    hCard2Badge: "ትምህርትን ስልጣነን",
    hCard2Title: "Education &amp; Civilisation",
    hCard2Text: "Education is the instrument through which culture becomes civilised, advanced, and sustainable. A society that educates its people well arms them with the tools to live with dignity, contribute to progress, and protect what is precious about their heritage.",
    hCard2L1: "Integrate cultural values into modern education",
    hCard2L2: "Raise the standard of learning for every child",
    hCard2L3: "Pair academic knowledge with moral character",
    hCard2L4: "Build schools as centres of cultural continuity",
    hCard3Badge: "ምስ ዓለም ምወዳደር",
    hCard3Title: "Global Competitiveness",
    hCard3Text: "We raise the next generation not to abandon their roots but to take those roots into the world and compete with confidence. A child grounded in culture and equipped with knowledge can stand anywhere in the world — bringing honour to their heritage while contributing to humanity.",
    hCard3L1: "Equip youth with skills for a global knowledge economy",
    hCard3L2: "Foster pride in heritage alongside openness to the world",
    hCard3L3: "Build partnerships that elevate our community globally",
    hCard3L4: "Create pathways: locally rooted, globally reaching",
    hActionTag: "ክንገብሮ ዝግበኣና · What We Must Do",
    hActionTitle: "Our Duty — What We Must Do",
    hActionDesc: "Five concrete obligations every generation carries to the next.",
    hStep1Title: "Confirm our social existence through deeds, not words",
    hStep1Text: "Existence is not declared — it is demonstrated. We confirm the reality of our community not by speaking about it but by living it: through the choices we make daily, the institutions we build, the values we practise in our homes, workplaces, and public life.",
    hStep2Title: "Restore our culture and history to their proper place",
    hStep2Text: "Cultures can drift from their true expression under outside pressure, neglect, or confusion. Our duty is to study, recover, and restore our cultural and historical understanding — returning it to the civilised, dignified form it deserves, advanced through honest education.",
    hStep3Title: "Teach the next generation our proper cultural methods",
    hStep3Text: "The next generation cannot inherit what they were never taught. Every elder, parent, teacher, and community leader carries the obligation to pass on — through example, story, institution, and practice — the correct and dignified methods of our culture.",
    hStep4Title: "Equip them with educated, advanced knowledge",
    hStep4Text: "Cultural grounding alone is not enough — it must be paired with the highest quality of modern, civilised education. We owe the next generation both roots and wings: deep cultural identity and the academic, technical, and moral formation that enables them to excel in any arena.",
    hStep5Title: "Make them able to compete with the world",
    hStep5Text: "The final measure of our generational duty is whether the young people we raise can stand with confidence in the global arena — not ashamed of their origins but strengthened by them. Every investment in education, culture, and character is an investment in a generation that can bring dignity to our community on the world stage.",
    hDuty: "It is our duty — to equip the next generation with educated, civilised, and advanced learning so they may stand, compete, and bring honour wherever they go.",
    // Faithful Witness
    sectionWitness: "We Are Faithful Witnesses",
    sectionWitnessDesc: "A solemn declaration rooted in classical Ge'ez — affirming our commitment to truth, trust, and faithful living.",
    witnessGeezTrans: "But we say to you — that we are indeed faithful and trustworthy believers.",
    witnessMeaningTitle: "What This Declaration Means",
    witnessMeaningP1: "This ancient Ge'ez phrase is a declaration of faithful witness. To say <em>\"ማእምራን እምንቱ\"</em> — \"we are faithful believers\" — is not merely a statement of religious belonging. It is a covenant: a commitment to be trustworthy in word, deed, and character.",
    witnessMeaningP2: "The word <em>\"ንቤለክሙ\"</em> — \"we say to you\" — gives this declaration a communal, outward direction. It is a witness made before others: we do not simply hold this truth privately — we declare it, live it, and invite others to hold us accountable to it.",
    wPillar1Badge: "ማእምራን ብቃል",
    wPillar1Title: "Faithful in Word",
    wPillar1Text: "To be a faithful witness begins with truthful speech. Every word we speak — in public and private, in promise and teaching — must reflect integrity. Faithful witness means saying what is true, even when it is difficult, and honouring what we have spoken.",
    wP1L1: "Speak truth even under pressure",
    wP1L2: "Keep promises and honour commitments",
    wP1L3: "Teach what is right and accurate",
    wP1L4: "Let your yes mean yes, and your no mean no",
    wPillar2Badge: "ማእምራን ብተግባር",
    wPillar2Title: "Faithful in Deed",
    wPillar2Text: "Words without deeds are hollow. Faithful witness is confirmed in action — in how we treat others, in the effort we invest, in the service we render to our community. The faithful person is recognised not by what they claim but by what they do, consistently, day after day, without audience.",
    wP2L1: "Act with consistency whether seen or unseen",
    wP2L2: "Serve your community without expectation of reward",
    wP2L3: "Follow through on every responsibility entrusted to you",
    wP2L4: "Let your life be your testimony",
    wPillar3Badge: "ማእምራን ለዘለዓለም",
    wPillar3Title: "Faithful Across Generations",
    wPillar3Text: "Faithful witness does not end with one life. The deepest fidelity is the one we keep to those who come after us — passing on truth, values, culture, and faith in a form that enables the next generation to be faithful witnesses in their own time. What we build today is the testimony they will inherit.",
    wP3L1: "Live in a way that the next generation can follow",
    wP3L2: "Pass on faith, values, and cultural truth intact",
    wP3L3: "Build institutions that outlast any individual",
    wP3L4: "Be the ancestor your descendants will honour",
    witnessPledgeTitle: "Our Declaration",
    wPledge1: "We declare ourselves faithful in word — we will speak truth.",
    wPledge2: "We declare ourselves faithful in deed — we will live what we profess.",
    wPledge3: "We declare ourselves faithful across generations — we will pass on what is true and good.",
    wPledge4: "We say to you — and we say to ourselves — that we are indeed faithful believers.",
    // Hope & Perseverance
    sectionHope: "Never Lose Hope",
    sectionHopeDesc: "In the entire world, the only true enemy of a human being is despair. Therefore, at any moment — never surrender, never lose hope.",
    hopeDecl: "In the world, the only enemy of a human being is despair — the cutting off of hope. Therefore, at any moment, never give up and never lose hope.",
    hpCard1Badge: "እንኮ ጸላኤ",
    hpCard1Title: "The Only Enemy",
    hpCard1Text: "Despair is named here as the singular enemy of every human being — not poverty, not failure, not opposition from others. Those forces can all be overcome. But despair — the inner decision to stop believing that things can change — is the one force that truly defeats a person before the battle has begun.",
    hpC1L1: "Despair closes the door before it has been tried",
    hpC1L2: "It is an inner defeat, not an outer one",
    hpC1L3: "Every other enemy can be faced and fought",
    hpC1L4: "Despair alone cannot be fought — only refused",
    hpCard2Badge: "ኤድካ ዘይምሃብ",
    hpCard2Title: "Never Give Up",
    hpCard2Text: "\"Never give up\" is not a slogan — it is a daily, deliberate act of resistance against the pull of despair. It means continuing to show up, to try, to act — even when results are slow, even when others doubt, even when you yourself feel the weight of difficulty. The act of continuing is itself the victory.",
    hpC2L1: "Continue even when progress is invisible",
    hpC2L2: "Show up again after every setback",
    hpC2L3: "Let perseverance be its own form of courage",
    hpC2L4: "The one who continues is never truly defeated",
    hpCard3Badge: "ተስፋ ዘይምቁራጽ",
    hpCard3Title: "Never Lose Hope",
    hpCard3Text: "Hope is not optimism — it is not the belief that everything will be easy. Hope is the deep conviction that effort and endurance matter, that tomorrow holds possibility, that the human spirit has reserves not yet spent. To never lose hope is to keep that conviction alive, protected, and shared — especially with those who are struggling.",
    hpC3L1: "Hope is a choice renewed every morning",
    hpC3L2: "Guard it — despair will always look for an opening",
    hpC3L3: "Share hope with those who are losing theirs",
    hpC3L4: "A community that keeps hope alive cannot be broken",
    hpWhyTag: "ስለምንታይ ተስፋ ይቕጽል · Why Hope Matters",
    hpWhyTitle: "Why We Must Never Cut Off Hope",
    hpWhy1Title: "It is the source of all action",
    hpWhy1Text: "No person acts without some belief that action is worth taking. Hope is the engine beneath every human effort — remove it and all motion stops. Sustaining hope is sustaining the capacity to change your situation.",
    hpWhy2Title: "It protects community",
    hpWhy2Text: "When one person loses hope, those around them feel it. When a community collectively loses hope, it fragments. A society that nurtures hope in its members — especially in the young — is a society that will endure and grow.",
    hpWhy3Title: "It turns pain into purpose",
    hpWhy3Text: "Hardship without hope is pure suffering. Hardship held within hope becomes a story — a test, a chapter, a force that shapes character. Hope gives difficulty a frame: this is not the end; this is the making of something better.",
    hpWhy4Title: "It is a duty to those who come after",
    hpWhy4Text: "Those who keep hope alive do not do so only for themselves. Every elder who models perseverance, every parent who refuses to despair, every young person who rises again after falling — they are keeping alive a fire the next generation will need.",
    hpAffirm: "At every moment — never surrender, never lose hope. This is our choice and our strength.",
    // Collective Growth
    sectionGrowth: "We Must Focus on Collective Growth",
    sectionGrowthDesc: "Collective growth creates abundant joy and happiness in our lives, and its results appear quickly and visibly. This is why we must make it our focus.",
    growthDecl: "We must focus on collective growth — because it creates much joy and happiness for us, and because its results appear swiftly and visibly. This is why I say this.",
    growthWhyTag: "ንምንታይ · Why",
    growthWhyTitle: "Why Collective Growth Matters",
    growthWhyIntro: "Shared progress is not just more effective than individual effort — it is richer, more joyful, and more durable. Here are the core reasons.",
    growthWhy1Title: "It creates joy and happiness",
    growthWhy1Text: "Growing together produces a feeling that individual achievement rarely can — the shared delight of watching people around you rise alongside you. Joy multiplies when it is witnessed and celebrated in community.",
    growthWhy2Title: "Its results appear swiftly",
    growthWhy2Text: "When people combine their skills, energy, and resources, the pace of progress accelerates dramatically. What one person might achieve in years, a committed collective can accomplish in months.",
    growthWhy3Title: "It builds lasting strength",
    growthWhy3Text: "A community that grows together builds roots — shared history, mutual trust, and structures that survive beyond any single individual. This is the kind of strength that one generation passes to the next.",
    growthWhatTag: "እንታይ ፍረ · What Results",
    growthWhatTitle: "The Visible Fruits of Collective Growth",
    growthWhatIntro: "These are the practical signs that collective growth is happening — the outcomes you can see, feel, and measure.",
    growthFruit1Title: "Stronger bonds",
    growthFruit1Text: "People who build together trust each other more deeply. Social fabric tightens, conflict drops, and cooperation becomes the norm.",
    growthFruit2Title: "Visible, shared prosperity",
    growthFruit2Text: "Resources and opportunities spread more widely. Prosperity is not concentrated in the hands of a few — it becomes visible across the whole community.",
    growthFruit3Title: "Shared purpose and direction",
    growthFruit3Text: "Growing together aligns people around common goals. This shared purpose gives meaning to daily effort and removes the isolation of working alone.",
    growthFruit4Title: "Resilience under pressure",
    growthFruit4Text: "Communities that have grown together withstand shocks — economic downturns, hardship, external pressures — far better than isolated individuals.",
    growthHowTag: "ከመይ ንተግብሮ · How To Practise",
    growthHowTitle: "Practical Steps Toward Collective Growth",
    growthHowIntro: "Collective growth does not happen automatically — it is built step by step, through deliberate choices and sustained habits.",
    growthStep1Title: "Shift from \"I\" to \"we\"",
    growthStep1Text: "The first and most fundamental step is a change in frame: begin every plan, every project, and every decision by asking not \"what do I gain?\" but \"what do we build?\" This mental shift changes the energy of everything that follows.",
    growthStep2Title: "Invest in others' capacity",
    growthStep2Text: "Active collective growth requires deliberately helping others rise. Share knowledge, open doors, mentor those behind you, and celebrate others' progress publicly. What you invest in others returns multiplied.",
    growthStep3Title: "Build shared projects and spaces",
    growthStep3Text: "Create tangible things together — a community initiative, a shared resource, a collective goal with milestones. Shared projects are the engine of shared identity. They give abstract values a concrete form people can see and touch.",
    growthStep4Title: "Celebrate collective wins visibly",
    growthStep4Text: "Every collective milestone deserves public recognition. Celebrating together reinforces that growth is shared, not individual. It signals to newcomers and doubters alike that this community moves — and that they are welcome to move with it.",
    growthAffirm: "Together we grow — creating abundant joy, happiness, and results that appear swiftly for all to see.",
    // Rest after Victory
    sectionRest: "When We Achieve Victory, We Deserve to Rest",
    sectionRestDesc: "Victory is not only a moment of triumph — it is the right to finally rest from the exhausting cycle of life's ups and downs. We have earned it. We must honour it.",
    restDecl: "When we have achieved victory — we should let our lives rest from the exhausting cycle of ups and downs.",
    restWhatTag: "ዓወት · What Victory Means",
    restWhatTitle: "What True Victory Looks Like",
    restWhatIntro: "Victory is not merely a single achievement — it is the culmination of sustained effort, sacrifice, and perseverance. Understanding what we have won changes how we receive the rest we deserve.",
    restPillar1Title: "The end of a long struggle",
    restPillar1Text: "True victory marks the close of a chapter filled with hardship. It is the moment when what once felt impossible has been made real through patience and relentless effort.",
    restPillar2Title: "Balance restored",
    restPillar2Text: "The constant oscillation between highs and lows is exhausting. Victory restores equilibrium — a steady ground to stand on, free from the anxiety of the next fall.",
    restPillar3Title: "A new beginning, freely chosen",
    restPillar3Text: "Once you have won, the next chapter belongs entirely to you — not driven by necessity or fear, but by choice, by joy, and by a life lived on your own terms.",
    restWhyTag: "ንምንታይ · Why Rest Matters",
    restWhyTitle: "Why We Must Rest after Victory",
    restWhyIntro: "Rest is not weakness and it is not surrender — it is the intelligent response to achievement. Here is why rest is essential after victory.",
    restWhy1Title: "The body and mind need recovery",
    restWhy1Text: "The energy spent to achieve victory is real. Every struggle consumes physical and mental reserves. Rest is not idleness — it is the repair process that makes the next chapter possible. Without it, we carry yesterday's exhaustion into tomorrow.",
    restWhy2Title: "Clarity returns with stillness",
    restWhy2Text: "When life is an endless cycle of struggle, we lose the ability to see clearly. Rest creates the stillness in which vision returns — where we can ask what we truly want next, not just what the crisis demands.",
    restWhy3Title: "It honours the victory itself",
    restWhy3Text: "Rushing immediately into the next battle dishonours what was just won. Pausing to rest is an act of gratitude — a conscious recognition that something real and meaningful has been achieved. It closes the chapter properly.",
    restHowTag: "ከመይ ዕረፍቲ · How to Rest Well",
    restHowTitle: "Practical Steps toward Meaningful Rest",
    restHowIntro: "Rest is a practice — it does not always come naturally after a long season of striving. These steps make it real and sustainable.",
    restStep1Title: "Name and receive the victory",
    restStep1Text: "Before rest can begin, the victory must be acknowledged — said aloud, shared with others, and truly received. Many people rush past their wins without pausing to take them in. Name what you have achieved. Let it land. Only then can rest begin from a place of genuine completion.",
    restStep2Title: "Create space free from striving",
    restStep2Text: "Rest requires that striving be consciously suspended — not forever, but for a defined season. Create literal space: quiet time, a slower pace, activities that restore rather than demand. Protect this space against the habit of constant productivity. Not every moment needs to be earned.",
    restStep3Title: "Reconnect with what brings simple joy",
    restStep3Text: "During seasons of struggle, simple pleasures are often postponed. Rest is the moment to return to them — relationships, creativity, nature, laughter, food shared with people you love. These are not rewards for the future. They are the substance of a life well lived, available now.",
    restStep4Title: "Let the next chapter emerge, don't force it",
    restStep4Text: "True rest means releasing the compulsion to immediately plan the next conquest. Allow yourself the unscheduled time to simply be. The next vision will emerge with far greater clarity and depth from a rested mind than from an exhausted one forcing answers. Trust the process of stillness.",
    restAffirm: "When victory is won — our lives deserve to rest from the exhaustion of the struggle. That rest begins now.",
  },
  ti: {
    heroTitle:    "ሰላምን ርክብን <span class='highlight'>ብሃብታምነት ባህሊ</span>",
    heroSubtitle: "ሓድሽ ሓሳባት ኣብ ዘመናዊ ዓለም ብምምዕባል፡ ሰላምን ዝሰምር ርክብን ኣብ መንጎ ዝተፈለዩ ባህልታት፡ ሕብረተሰባትን ሃገራትን ንምርግጋጽ።",
    pillar1Title: "ሰላምን ዘተን",
    pillar1Text:  "ኣብ ሓፈሻዊ ዘተ ዝሕግዙ መኣዲ ምፍጣር ኣብ መንጎ ዝተፈለዩ ባህልታት፡ ዓሌታትን ሃገራትን።",
    pillar2Title: "ፍትሕን ማዕርነትን",
    pillar2Text:  "ሲቪላዊ መሰላት፡ ልዕልና ሕጊን ማዕረ ክብርን ንነፍሲ ​​ወከፍ ሰብ ምኽባር።",
    pillar3Title: "ልውውጥ ባህሊ",
    pillar3Text:  "ብጥበብ፡ ቋንቋ፡ ወግዒን ሓባራዊ ተሞክሮታትን ፍልልይ ምኽባር።",
    pillar4Title: "ጽንዓትን ዕቤትን",
    pillar4Text:  "ርእሰ ምትእምማን ካብ ፍሽለት ናጽነት ኣይኮነን — ደጊምካ ናብ ሓድሽ ልዕሊ ምብጻሕ እዩ።",
    sectionCultures: "ባህልታት ዓለም",
    sectionCulturesDesc: "ነፍሲ ወከፍ ባህሊ ጥበብ ኣለዎ። ሓቢርና ዝያዳ ሓይሊ ኣለና።",
    sectionJustice: "ፍትሕን መሰላትን",
    sectionJusticeDesc: "ፍትሒ ናይ ቀዋሚ ሰላም ናይ ህዝቢ ሰረት እዩ።",
    joinTitle: "ናብ ምንቅስቓስ ተጸምበር",
    joinDesc: "ንሰላም፡ ምፍልላጥን ሰሪሖም ርክብን ዝቆረጸ ዓለምለኻዊ ማሕበረሰብ ተሳታፍ።",
    sectionFaith: "ምስ ፈጣሪ ምጓዕዞ",
    sectionFaithDesc: "ነብስ ወከፍ ጉዕዞና ኣብ ፈጣሪ ዝተመርኮሰ ክኸውን ይግበኣና ።",
    faithVerse1: "ነብስ ወከፍ ጉዕዞና ኣብ ፈጣሪ ዝተመርኮሰ ክኸውን ይግበኣና ።",
    faithVerse2: "ምክንያቱ ፈጣሪ ዘይተሓወሶ መንገድን ጉዕዞ ሂወትን ከቢድን ኣይከኣልን እዩ ።",
    faithVerse3: "ስለዚ ንዓወትና ንነብስናን ክሕሸና ክንብል ምስፈጣሪ ክንጓዓዝ ይግበኣና ።",
    // Self-Reliance section
    sectionReliance: "ህላወ ኣብ ርእሰ ምርኮሳ",
    sectionRelianceDesc: "ምስ ከመይ ኩነታት ሰብ ብናጽነትን ውሽጣዊ ሓይልን ክነብር ይኽእል?",
    relianceLead: "ህላወ ኣብ ርእሰ ምርኮሳ ማለት ብሕቲ ምስራሕ ኣይኮነን። ኣብ ፈጣሪ ዝተሰረተ፡ ብፍልጠት ዝተዓጠቀ፡ ብሕብረተሰብ ዝተሓለወ፡ ብፍትሒ ዝተቐረበ ሰብ — ብናጽነት ዝነብር ሰብ እዩ ።",
    reliance1Title: "ናይ ፈጣሪ ሰረት",
    reliance1Text: "ህይወት ኣብ ፈጣሪ ምስርሳር ንጹርነት፡ ትብዓትን ኣቅጣጫን ይህብ ። ብዘይ እዚ ሰረት፡ ናይ ህይወት ጉዕዞ ከቢድን ርሑቕን እዩ ።",
    reliance2Title: "ውሽጣዊ ሓይልን ጽንዓትን",
    reliance2Text: "ርእሰ ምትእምማን ካብ ፍሽለት ናጽነት ኣይኮነን — ደጊምካ ናብ ሓድሽ ምብጻሕ እዩ ። ጽንዓት ናይ ርእሰ ምርኮሳ ቀንዲ ሰረት ።",
    reliance3Title: "ፍልጠትን ጥበብን",
    reliance3Text: "ትምህርቲን ምምሃርን ዝዓጸዉ ማዕጾ ይኸፍቱ ። ፍልጠት ዝዓጠቀ ሰብ ብናቱ ኣቕጣጫ ህይወቱ ይምርሕ ።",
    reliance4Title: "ሕብረተሰብን ሓቢርካ ምቕማምን",
    reliance4Text: "ሓቀኛ ርእሰ ምርኮሳ ብሕቲ ኣይርከብን ። ሓያል ሕብረተሰብ ነፍሲ ​​ወከፍ ሰብ ኣብ ርእሱ ዝቅሞ ሓይሊ ይህቦ ።",
    reliance5Title: "ፍትሕን ማዕረ ዕድልን",
    reliance5Text: "ፍትሓዊ ኩነታት ሕብረተሰብ — ልዕልና ሕጊ፡ ማዕረ ዕድልን ሲቪላዊ መሰላትን — ኩሉ ሰብ ናብ ርእሰ ምርኮሳ ዝኸደሉ ዕድል ።",
    developTag: "ብከመይ ምምዕባል · ብኸምዚ ምምዕባሉ",
    developTitle: "ርእሰ ምርኮሳ ብከመይ ትምዕብሎ?",
    developDesc: "ናይ ዕለት ዕለት ስጉምቲታት — ነፍሲ ወከፍ ናይ ናጻ ሕይወት ኣካል ።",
    step1Title: "ኣብ ፈጣሪን ናይ ሕይወት ትርጉምን ምስርሳር",
    step1Text: "ነፍሲ ወከፍ መዓልቲ ኣብ ጸሎትን ምሕሳብን ጀምር ። ፈጣሪ ናይ ሂወትካ ኣቅጣጫ ኣለዎ — ናቱ ናቅ ፍቐዶ ።",
    step2Title: "ናይ ዕለት ዕለት ርእሰ ቁጽጽር ምምዕባል",
    step2Text: "ዕላማ ኣውጽእ፡ ናይ ዕለት ዕለት ስርዓት ምዕባዩ ። ኣሽቱ ልምድታት ዝዓበዩ ናጽነት ዘምጽኡ ።",
    step3Title: "ዕምሩ ምምሃር ምቅጻል",
    step3Text: "ኣብ ምምሃር ኣይደው ። ፍልጠት ናይ ርእሰ ምርኮሳ ዋጋ እዩ — ዝበዝሐ ዝተምሃርካ፡ ዝዛሓ ናጻ ።",
    step4Title: "ናይ ገንዘብ ፍልጠትን ሓላፍነትን ምምዕባል",
    step4Text: "ናይ ገንዘብ ፍልጠት ኣምዕብሉ — ምቁጣብ፡ ዕዳ ምርካብ ምምሕያሽ፡ ሃብቲ ምህናጽ ። ናይ ኢኮኖሚ ናጽነት ናይ ርእሰ ምርኮሳ ሓደ ቀንዲ መለክዒ እዩ ።",
    step5Title: "ዘዕቢኡ ዝምድናታት ምምዕባል",
    step5Text: "ዘዕቢኡ ዝምድናታት ምምዕባሉ — ዝሕግዙ፡ ዝደፋፍኡ፡ ናብ ዓቢ ሰብ ዝቕይሩ ።",
    step6Title: "ናይ ምርጫታትካ ምሉእ ሓላፍነት ምወሳድ",
    step6Text: "ናይ ርእስኻ ምርጫታትን ውጺኢቶምን ሓላፍነት ወስድ ። ናትካ ሕይወት ብናትካ ኢድ ።",
    step7Title: "ካልኦት ምሕጋዝ — ናብ ሕብረተሰብ ምምላስ",
    step7Text: "ናይ ርእሰ ምርኮሳ ፍሬ — ካልኦት ምሕጋዝ ። ካልኦት ኣብ ርእሶም ምቃም — ናትካ ሰረት ዘደልዳሉ ።",
    relianceClosing: "ርእሰ ምርኮሳ ስጉምቲ ብስጉምቲ ይህነጽ — ብእምነት፡ ስርዓት፡ ምምሃር፡ ሓላፍነትን ንካልኦት ምሕጋዝን ።",
    // Governance section
    sectionGov: "ስነ ምሕደራ እንታይ ማለት እዩ?",
    sectionGovDesc: "ናይ ርእሰ ምሕደራ፡ ሕብረተሰብን ትካላትን ምሕደራ — ትርጉሙን ኣሰራርሕኡን ።",
    govDefHeading: "ስነ ምሕደራ — ትርጉምን ሰረቱን",
    govDefP1: "ስነ ምሕደራ ማለት — ሕብረተሰብ፡ ትካልን ሃገርን ብስርዓት፡ ብሕጊ፡ ብሓቀኛ ናይ ሓቢርካ ኣሰራርሓን ዝምዳን ዝካየደሉ ኣሰራርሓ እዩ ።",
    govDefP2: "ሓቀኛ ምሕደራ ጥራሕ ስልጣን ይሕዝ ዝብል ኣይኮነን — <em>ስልጣን ብኸምዚ</em> ይካየድ ማለት ። ብንጽህና፡ ሓላፍነትን ፍትሕን ።",
    govP1: "ንጽህና", govP1Sub: "Transparency",
    govP2: "ሓላፍነት", govP2Sub: "Accountability",
    govP3: "ተሳትፎ", govP3Sub: "Participation",
    govP4: "ልዕልና ሕጊ", govP4Sub: "Rule of Law",
    govP5: "ውጽኢታዊነት", govP5Sub: "Effectiveness",
    govP6: "ፍትሒ", govP6Sub: "Justice",
    govHowTag: "ብከመይ ይካየድ · ኣሰራርሓ",
    govHowTitle: "ርእሰ ምሕደራ ብከመይ ይካየድ?",
    govHowDesc: "ሽድሽተ ቀንዲ ኣሰራርሓ — ካብ መትከላት ናብ ተግባር — ሓቀኛ ርእሰ ምሕደራ ዘትርር ።",
    govStep1Title: "ንጹር መትከላትን ሓባራዊ ክብርታትን ምምጻእ",
    govStep1Text: "ርእሰ ምሕደራ ካብ ዝተሰማምዑሉ ክብርታት ይጅምር — ሓቅነት፡ ክብርን፡ ፍትሕን ። እዚ ክብርታት ናይ ኩሉ ምሕደራ ቅዋም እዩ ።",
    govStep2Title: "ንጹር ትካላዊ ቅርጽን ዝፈለጡዎ ዕማምን ምምጻእ",
    govStep2Text: "ሓደ ዝፈለጡዎ ዕማምን ሓላፍነትን ዘለዎም ትካላዊ ቅርጺ — ናይ ምሕደራ ሰረት ። ኩሉ ሰብ ናቱ ዕማም ዝፈልጠሉ ስርዓት ምምጻእ ።",
    govStep3Title: "ሓላፍነትን ክትትልን ምርጋጽ",
    govStep3Text: "ሓለፍቲ ናይ ዝወስዶዎ ውሳነ ሓላፍነት ዝወስዱሉ ስርዓት ምምጻእ — ርእሰ ምሕደራ ካብ ዕሱብ ዝሕሉ ።",
    govStep4Title: "ሰፊሕ ተሳትፎን ምርኻብን ምስምጻእ",
    govStep4Text: "ናይ ኩሎም ድምጺ ዝሰምዕ ምሕደራ — ናይ ህዝቢ ምሕደራ እዩ ። ምርጫ፡ ምምኻር፡ ቁሊሕ ምዝራብ — ናይ ርእሰ ምሕደራ ኣካላት ።",
    govStep5Title: "ልዕልና ሕጊ ማዕረ ምኽባር",
    govStep5Text: "ሕጊ ንኩሉ ሰብ ማዕረ ዝምልከት ክኸውን ኣለዎ — ሓይለኛ ኮነ ድኹም ። ልዕልና ሕጊ — ናይ ርእሰ ምሕደራ ዓምዲ ።",
    govStep6Title: "ቀጻሊ ምምሃርን ምምሕያሽን",
    govStep6Text: "ርእሰ ምሕደራ ኣይውዳእን — ዘሻሻሉ፡ ካብ ጌጋ ዝምሃሩ፡ ዝዓቢ ስርዓት ዝምህ ። ቀጻሊ ምምሕያሽ ናይ ሓቀኛ ምሕደራ ምልክት ።",
    govClosing: "ነፍሲ ​​ወከፍ ዓይነት ምሕደራ ብናይ ሕብረተሰቡ ባህልን እምነትን ዝምዘን ። ሓቀኛ ምሕደራ — ፋይናንሳዊ፡ ህዝባዊ ወይ ሃይማኖታዊ — ኣብ ፍትሒ፡ ንጽህናን ሓላፍነትን ዝተሰረተ ።",
    govTypesTag: "ዝተፈላለዩ ዓይነት ምሕደራ · ዓይነታት",
    govTypesTitle: "ዝተፈላለዩ ዓይነት ምሕደራ",
    govTypesDesc: "ምሕደራ ኣብ ዝተፈላለዩ ሕብረተሰባት ዝተፈላለዩ ቅርጽታት ኣለዎ — ነፍሲ ​​ወከፍ ብናይ ሕብረተሰቡ ባህልን ክብርታትን ዝምዘን ።",
    govType1Badge: "ናይ ፋይናንሳዊ ምሕደራ",
    govType1Title: "ፋይናንሳዊ ምሕደራ",
    govType1Text: "ፋይናንሳዊ ምሕደራ — ሃብቲ፡ ገንዘብን ኢኮኖሚያዊ ዕድላትን ብናይ ሓደ ትካል፡ ሕብረተሰብ ወይ ሃገር ዝካየዱሉ ስርዓትን ኣሰራርሓን ።",
    govType1L1: "ባጀትን ናይ ፋይናንስ ሓላፍነትን",
    govType1L2: "ናይ ወጻኢታት ንጽህናን ምቁጽጻርን",
    govType1L3: "ናይ ሃብቲ ፍትሓዊ ምምቅቃል",
    govType1L4: "ኣቃጻጽሮ ኣቃጻጽሮ ምምካቱ",
    govType1L5: "ናይ ነዊሕ ግዜ ኢኮኖሚያዊ ምድላው",
    govTypeCultureLabel: "ናይ ባህሊ ርክብ፡",
    govType1Culture: "ነፍሲ ​​ወከፍ ሕብረተሰብ ኣብ ዙሪያ ሃብቲ፡ ምምቅቃልን ፍትሕን ዝተሰረቱ ክብርታት ኣለዎ ። ፋይናንሳዊ ምሕደራ ናይ ሕብረተሰብ ናይ ፍትሒ ኣረኣእያ ዘንጸባርቕ ክኸውን ኣለዎ ።",
    govType2Badge: "ህዝባዊ ምሕደራ",
    govType2Title: "ህዝባዊን ስርዓታዊን ምሕደራ",
    govType2Text: "ህዝባዊ ምሕደራ — መንግስቲ፡ ትካላትን ሲቪላዊ ኣካላትን ናይ ኩሎም ዜጋታት ጠቕሚ ዘርኢ ኣገልጋሎት ዝህቡሉ፡ መሰላት ዝሕልዉሉ፡ ሓባራዊ ጉዳያት ዝካይዱሉ ስርዓት ።",
    govType2L1: "ዲሞክራስያዊ ምርጫን ውክልናን",
    govType2L2: "ልዕልና ሕጊን ቅዋማዊ ስርዓትን",
    govType2L3: "ናይ ህዝቢ ኣገልጋሎት ምሃብ",
    govType2L4: "ሲቪላዊ መሰላትን ምሕላው ውሑዳትን",
    govType2L5: "ምምቅቃል ስልጣንን ናይ ቁጽጽር ስርዓትን",
    govType2Culture: "ህዝባዊ ምሕደራ ብናይ ሕብረተሰብ ታሪኽ፡ ልምዲን ክብርታትን ዝቐርጸ እዩ ። ሓቀኛ ስልጣን ካብ ህዝቢ ዝምንጩ — ሕብረተሰብ ናቱ ሕጊ ዝፈጥር ።",
    govType3Badge: "ሃይማኖታዊ ምሕደራ",
    govType3Title: "ሃይማኖታዊ ምሕደራ",
    govType3Text: "ሃይማኖታዊ ምሕደራ — ናይ እምነት ሕብረተሰባት፡ ሃይማኖታዊ ትካላትን መንፈሳዊ ልምድታትን ዝምርሕሉን ዝካየዱሉን — ናይ ምሕደራ፡ ናይ ሕብረተሰብ ናይ ርክብ ኣካይዳ ።",
    govType3L1: "ናይ ምሕደራ ስነ ምግባርን ኣሰራርሓን",
    govType3L2: "ናይ መሪሕነት ቅርጺ — ሓለፍቲ ሃይማኖት፡ ዓበይቲን ኮሚቴታትን",
    govType3L3: "ናይ ምንቅስቓስ ፍታሕ ብናይ እምነት ትምህርቲ",
    govType3L4: "ናይ ሕብረተሰብን ናይ ምሕረትን ዕማም ምምሕዳር",
    govType3L5: "ናይ መንፈሳዊ ሓላፍነት ኣብ ቅድሚ ፈጣሪ",
    govType3Culture: "ኣብ ብዙሓት ሕብረተሰባት ሃይማኖትን ምሕደራን ኣይፈለን — ሕጊ፡ ስድራ ቤት ቅርጽን ናይ ሕብረተሰብ ዕማምን ዝቐርጽ ። ናይ እምነት ዕምቆት ምርዳእ ናይ ሓቀኛ ምሕደራ ኣካል ።",
    govTypesNote: "<strong>ነፍሲ ​​ወከፍ ዓይነት ምሕደራ ብናይ ሕብረተሰቡ ባህልን እምነትን ዝምዘን ።</strong> ሓደ ሞዴል ንኩሉ ሕብረተሰብ ኣይሰርሕን ። ሓቀኛ ምሕደራ ካብ ህዝቢ ዝምንጩ — ኣይምልምቱን ። ፍትሕን ሓቀኛ ናይ ሕብረተሰብ ክብርታትን ዝሰምር ምሕደራ ጥራሕ ዘቐምጥ ።",
    // Cultural Heritage & Generational Duty
    sectionHeritage: "ህላወ ሕብረተሰብናን ባህልናን — ሓላፍነትና",
    sectionHeritageDesc: "ህላወ ናይ ሕብረተሰብናን ብግብሪ ከነረጋግጾ ይግበኣና — ባህልናን ታሪኽናን ናብ ንቡሩ ምምላስ፡ ዳሕረዋይ ወለዶ ምዕጣቕን ምልምሳን ።",
    heritageDecl: "ህላወ ናይ ሕብረተሰብናን ብግብሪ ከነረጋግጾ ይግበኣና ኣብ ዝኾነ መዳያት ናይ ሂወትና ። ቀዳምነት ክንህቦ ዝግበኣና ነገር — ብትምህርቲ ዝተሰነየ ምዕቡልን ስልጡንን ባህልናን ታሪኽናን ናብ ንቡር ምምላስ ። ንዳሕረዋይ ወለዶ እቲ ግቡእን ኣገባብ ባህልናን ምስልጣን፡ ምስ ዓለም ክወዳደር ከምዝኽእሉ ጌርና ትምህርትን ስልጡን ምዕቡልን ትምህርቲ ምዕጣቖም — ግዴታና እዩ ።",
    hCard1Badge: "ባህልናን ታሪኽናን",
    hCard1Title: "ባህልና ታሪኽና",
    hCard1Text: "ባህልናን ታሪኽናን ናይ መን ምዃና ሰረት እዩ ። ካብ ወለዶ ናብ ወለዶ ዝሰጋገር ጥበብ፡ ክብርታትን ውልቀ ሰነ ድዩ ካብ ዝፍጠር — ህያው ውርሻ ዝርዳእ፡ ዝኽበርን ኣብ ነፍሲ ​​ወከፍ ዓቕሚ ዝምህርን ።",
    hCard1L1: "ናይ ኣፍ ልሳን ትምህርቲ፡ ጽሑፍን ቋንቋን ምሕላው",
    hCard1L2: "ናይ ታሪኽና ዛንታ ምጽሕፍን ምምሃርን",
    hCard1L3: "ኣብ ናይ ባህሊ ኣሰራርሓ ዝሰረቱ ክብርታት ምኽባር",
    hCard1L4: "ባህሊ ናብ ናቱ ቅኑዕ ስልጡን ኣገላልጻ ምምላስ",
    hCard2Badge: "ትምህርትን ስልጣነን",
    hCard2Title: "ትምህርቲን ስልጣነን",
    hCard2Text: "ትምህርቲ ባህሊ ስልጡንን ምዕቡልን ዝዕቅቦ ኣሳይሻ እዩ ። ሕብረተሰብ ህዝቡ ጽቡቕ ዝምሃሮ — ብክብርን ምዕቡል ሕይወትን ዝነብሩ፡ ናብ ምዕባሌ ዝወስኩ፡ ናይ ባህሎም ዋጋ ዝሕልዉ ሰባት ዘዕጥቕ ።",
    hCard2L1: "ናይ ባህሊ ክብርታት ምስ ዘናዊ ትምህርቲ ምዋሃድ",
    hCard2L2: "ናይ ምምሃር ደረጃ ንነፍሲ ​​ወከፍ ቆልዓ ምብራኽ",
    hCard2L3: "ናይ ትምህርቲ ፍልጠት ምስ ሞራላዊ ባህርይ ምዋሃዱ",
    hCard2L4: "ቤት ትምህርቲ ናይ ባህሊ ቀጻልነት ማእከላት ምህናጽ",
    hCard3Badge: "ምስ ዓለም ምወዳደር",
    hCard3Title: "ምስ ዓለም ምወዳደር",
    hCard3Text: "ዳሕረዋይ ወለዶ ናይ ባህሉ ሰረት ክሓድጎ ኣይኮነን — ናብ ዓለም ወሲዱ ብምትእምማን ዝወዳደር ። ኣብ ባህሉ ዝሰረተ፡ ብፍልጠት ዝዓጠቐ ቆልዓ ኣብ ዝኾነ ቦታ ዓለም ክቐምጥ ይኽእል ።",
    hCard3L1: "ንወጣሩ ናይ ዓለምለኻዊ ፍልጠት ቁጠባ ክእለት ምዕጣቕ",
    hCard3L2: "ኣብ ናይ ባህሊ ሓበን ምስ ናብ ዓለም ምዝርጋሕ ምዋሃዱ",
    hCard3L3: "ናይ ሕብረተሰብና ዓቕሚ ዓለምለኻዊ ዝዕብዩ ዝምድናታት ምህናጽ",
    hCard3L4: "ኣብ ናይ ቦታ ሰረት ዝተሰረቱ ዓለምለኻዊ ዝበጽሑ መንገዲ ምፍጣር",
    hActionTag: "ክንገብሮ ዝግበኣና · ሓላፍነትና",
    hActionTitle: "ሓላፍነትና — ክንገብሮ ዝግበኣና",
    hActionDesc: "ሓሙሽተ ዝተሓሰቡ ሓላፍነታት ነፍሲ ​​ወከፍ ወለዶ ናብ ቀጺሉ ዝወስዶ ።",
    hStep1Title: "ህላወ ሕብረተሰብናን ብቃላት ዘይኮነ ብተግባር ምርጋጽ",
    hStep1Text: "ህላወ ብድምጺ ኣይምስከርን — ብተግባር ። ህላወ ናይ ሕብረተሰብናን ብዛዕባኡ ብምዝራብ ዘይኮነ ብምንባሩ ንርጋጸሉ ። ብናይ ዕለት ዕለት ምርጫታትና፡ ዝህንጽናዮ ትካላት፡ ኣብ ገዛና ዝጥቀምናሉ ክብርታት ።",
    hStep2Title: "ባህልናን ታሪኽናን ናብ ናቱ ቦታ ምምላስ",
    hStep2Text: "ባህሊ ካብ ሓቀኛ ኣገላልጽኡ ብናጻ ጸቕጢ፡ ሸለልትነትን ምፍርርትን ክርሕቕ ይኽእል ። ሓላፍነትና ባህልናን ታሪኽናን ምምምህርን ምምላስን ። ናብቲ ዝግብኦ ስልጡን ደረጃ ብቅኑዕ ትምህርቲ ምምላሱ ።",
    hStep3Title: "ዳሕረዋይ ወለዶ ቅኑዕ ኣገባብ ባህልና ምምሃር",
    hStep3Text: "ዳሕረዋይ ወለዶ ዘይተምሃሮ ኣይወርስን ። ዝኾነ ዓቢ ሰብ፡ ወላዲ፡ መምህር፡ ናይ ሕብረተሰብ መሪሕ — ብምስክርነት፡ ዛንታ፡ ትካልን ተሞክሮን ቅኑዕ ኣገባብ ባህልና ናብ ቀጺሉ ወለዶ ናይ ምሕላፍ ሓላፍነት ኣለዎ ።",
    hStep4Title: "ብምዕቡልን ስልጡንን ፍልጠት ምዕጣቖም",
    hStep4Text: "ናይ ባህሊ ሰረት ጥራሕ ዘይኣኽል — ምስ ዝለዓለ ደረጃ ዘናዊ ስልጡን ትምህርቲ ዝተዋሃደ ክኸውን ኣለዎ ። ዳሕረዋይ ወለዶ ሰረትን ክንፍን ክህልዎ ይግበኣና — ዕምቆት ናይ ባህሊ መንነትን ናይ ትምህርቲ ምሕዛን ።",
    hStep5Title: "ምስ ዓለም ዝወዳደሩ ምግባሮም",
    hStep5Text: "ናይ ወለዶ ሓላፍነትና ዝለዓለ ምልካዕ — ዝዓበዩ ወጣሩ ኣብ ዓለምለኻዊ ቦታ ብምትእምማን ዝቐምጡ ። ካብ ሰረቶም ዘፍርሑ ዘይኮኑ — ብሰረቶም ዝሓይሉ ። ኣብ ትምህርቲ፡ ባህልን ባህርይን ዘሎ ወፍሪ ናብ ዓለም ዝወዳደር ወለዶ ናይ ምህናጽ ወፍሪ ።",
    hDuty: "ግዴታና እዩ — ንዳሕረዋይ ወለዶ ትምህርትን ስልጡን ምዕቡልን ትምህርቲ ምዕጣቖም ምስ ዓለም ዝወዳደሩ፡ ክብሪ ዘምጽኡን ።",
    // Faithful Witness
    sectionWitness: "ማእምራን እምንቱ — ምስክርነት እምነትና",
    sectionWitnessDesc: "ካብ ጥንታዊ ግዕዝ ዝምዕቆ ምስክርነት — ናብ ሓቂ፡ እምነትን ናይ ሓቅ ሕይወትን ዘለና ቃልኪዳን ።",
    witnessGeezTrans: "ነገር ግን ንቤለክሙ ከመ ንህነ ሰ ማእምራን እምንቱ — ብሓቂ እምነታውያን ምዃና ።",
    witnessMeaningTitle: "እዚ ምስክርነት እንታይ ትርጉም ኣለዎ",
    witnessMeaningP1: "እዚ ጥንታዊ ናይ ግዕዝ ሓሳብ ናይ እምነታዊ ምስክርነት ምርጋጽ እዩ ። <em>\"ማእምራን እምንቱ\"</em> ምባል — \"እምነታውያን ኢና\" — ጥራሕ ናይ ሃይማኖት ኣባልነት ምዃን ኣይኮነን ። ቃልኪዳን እዩ — ብቃሉ፡ ብተግባሩን ብባህርዩን እምነታዊ ምዃን ።",
    witnessMeaningP2: "<em>\"ንቤለክሙ\"</em> — \"ንቤለኩም\" — ናብ ካልኦት ዝቐንዐ ምስክርነት ። ኣብ ቅድሚ ካልኦት ዝምስከር ። ሓቂ ጥራሕ ብሕትና ዘይሕዙ — ንምስክሩ፡ ይነብሩሉ፡ ካልኦት ናብ ሓላፍነቶም ዝጽወዑሉ ።",
    wPillar1Badge: "ማእምራን ብቃል",
    wPillar1Title: "ብቃሉ እምነታዊ",
    wPillar1Text: "እምነታዊ ምስካር ካብ ሓቀኛ ዘረባ ይጅምር ። ዝዛረቦ ቃሉ — ኣብ ሕዝቢ ኮነ ብሕቲ፡ ኣብ ቃልኪዳን ኮነ ኣብ ምምሃር — ሓቅነት ዘንጸባርቕ ክኸውን ኣለዎ ። ሓቀኛ ምስካር — ሓቂ ምዝራብ፡ እኳ ምስ ከቢድ ।",
    wP1L1: "ኣብ ትሕቲ ጸቕጢ እኳ ሓቂ ምዝራብ",
    wP1L2: "ቃልኪዳን ምሕላው፡ ዝወዓሉ ምኽባር",
    wP1L3: "ቅኑዕን ሓቀኛን ምምሃር",
    wP1L4: "እወ ካብ እወ ኣሉ ካብ ኣሉ ምዃን",
    wPillar2Badge: "ማእምራን ብተግባር",
    wPillar2Title: "ብተግባሩ እምነታዊ",
    wPillar2Text: "ቃሉ ብዘይ ተግባር ቀፋፍ ። እምነታዊ ምስካር ብተግባር ዝምስከር — ኣብ ናይ ካልኦት ኣሰራርሓ፡ ኣብ ዘፍሰሶ ጻዕሪ፡ ኣብ ዘርኣዮ ናይ ሕብረተሰብ ኣገልጋሎት ። ሓቀኛ ሰብ ብዝብሎ ዘይኮነ — ብዝገብሮ ዝፍለጥ ።",
    wP2L1: "ዝርኣዮ ኮነ ዘይርኣዮ ብቕኑዕ ምስራሕ",
    wP2L2: "ብዘይ ናይ ዋጋ ትጽቢት ሕብረተሰብ ምግልጋል",
    wP2L3: "ዝተቐበሎ ሓላፍነት ኩሉ ምፍጻም",
    wP2L4: "ሕይወቱ ናቱ ምስክርነት ምዃን",
    wPillar3Badge: "ማእምራን ለዘለዓለም",
    wPillar3Title: "ናብ ዝቕጽሉ ወለዶ እምነታዊ",
    wPillar3Text: "እምነታዊ ምስካር ብሓደ ሕይወት ኣይውዳእን ። ዝዓሚቕ እምነት — ናብ ዝቕጽሉ ዝሕልዎ ። ሓቂ፡ ክብርታት፡ ባህልን እምነትን ዝቕጽሉ ወለዶ ብናቶም ዘምናዊ ምስካር ዘርኢ ቅርጺ ምሕላፍ ። ሎሚ ዝህነጽ ናይ ጽባሕ ምስክርነቶም ።",
    wP3L1: "ዝቕጽሉ ወለዶ ዝስዕቡ ህይወት ምምራሕ",
    wP3L2: "እምነት፡ ክብርታትን ናይ ባህሊ ሓቂን ሙሉእ ምሕላፍ",
    wP3L3: "ዝኾነ ሰብ ዝሓልፍ ትካላት ምህናጽ",
    wP3L4: "ዝቅጽሉ ወለዶ ዝሽልሙዎ ኣቦ ምዃን",
    witnessPledgeTitle: "ምስክርነትና",
    wPledge1: "ብቃልና እምነታውያን ምዃን ንምስክር — ሓቂ ክንዛረብ ።",
    wPledge2: "ብተግባርና እምነታውያን ምዃን ንምስክር — ዝምስከርናዮ ክንነብሮ ።",
    wPledge3: "ናብ ዝቕጽሉ ወለዶ እምነታውያን ምዃን ንምስክር — ሓቀኛን ጽቡቕን ክናሕልፍ ።",
    wPledge4: "ንቤለክሙ — ናብ ርእስና እውን ንብሎ — ሓቀኛ እምነታውያን ምዃና ።",
    // Hope & Perseverance
    sectionHope: "ተስፋ ዘይምቁራጽ",
    sectionHopeDesc: "ኣብ ዓለም እቲ እንኮ ጸላኤ ናይ ወዲ ሰብ ተስፋ ምቁራጽ እዩ ። ስለዚ ኣብ ዝኾነ ህሞት ኤድካ ዘይምሃብን ተስፋ ዘይምቁራጽን ።",
    hopeDecl: "ኣብ ዓለም እቲ እንኮ ጸላኤ ናይ ወዲ ሰብ ተስፋ ምቁራጽ እዩ ። ስለዚ ኣብ ዝኾነ ህሞት ኤድካ ዘይምሃብን ተስፋ ዘይምቁራጽን ።",
    hpCard1Badge: "እንኮ ጸላኤ",
    hpCard1Title: "እንኮ ጸላኤ",
    hpCard1Text: "ተስፋ ምቁራጽ — ናይ ወዲ ሰብ ጸላኤ ብምባሉ ዝፍለጥ ። ድኽነት ኣይኮነን፡ ፍሽለት ኣይኮነን፡ ካብ ካልኦት ዝምጹ ተጻብኦ ኣይኮነን ። እዞም ሓይሊታት ኩሎም ዝስዕሩ ። ተስፋ ምቁራጽ ግን — ናይ ውሽጢ ወሳኒ — ነገራት ክቕየሩ ዝኽእሉ ምዃኖም ኣብ ዘቋረጽናሉ — ቅድሚ ምውዳቕ ዘምርጽ ።",
    hpC1L1: "ተስፋ ምቁራጽ ዝተፈተነ ዘይብሉ ማዕጾ ይዓጽዎ",
    hpC1L2: "ናይ ውሽጢ ምዕዋት — ናይ ደገ ኣይኮነን",
    hpC1L3: "ካልእ ዝኾነ ጸላኤ ክዋጋእ ይከኣል",
    hpC1L4: "ተስፋ ምቁራጽ ጥራሕ ኣይዋጋእን — ይነፍጎ ጥራሕ",
    hpCard2Badge: "ኤድካ ዘይምሃብ",
    hpCard2Title: "ኤድካ ዘይምሃብ",
    hpCard2Text: "ኤድካ ዘይምሃብ ዕለታዊ ሃሳዪ ኣሰራርሓ ናብ ተስፋ ምቁራጽ ዝጻዕዋ ። ምቕጻል — ምፍታን — ምሥራሕ — እኳ ፍርያት ዝዘሓለ ምስ ዝኸውን፡ እኳ ካልኦት ምስ ዝጠርጥሩ፡ እኳ ናትካ ዓቕሚ ምስ ዝሸክምካ ። ምቕጻሉ ባዕሉ ዓወት እዩ ።",
    hpC2L1: "ምዕባሌ ዘይረኣዮ ምስ ዝኸውን እኳ ምቕጻል",
    hpC2L2: "ኣብ ዝኾነ ምልስ ምሃብ ድሕሪ ምዕዋት ምምላስ",
    hpC2L3: "ጽንዓት ናቱ ናይ ጅግንነት ቅርጺ ምዃን ምፍቓድ",
    hpC2L4: "ዝቕጽሉ ብሓቁ ዝዕወቱ ኣይኮኑን",
    hpCard3Badge: "ተስፋ ዘይምቁራጽ",
    hpCard3Title: "ተስፋ ዘይምቁራጽ",
    hpCard3Text: "ተስፋ ብሩኽ ኣተሓሳስባ ኣይኮነን — ኩሉ ቀሊል ምዃኑ ምእማን ኣይኮነን ። ተስፋ ጸዊዕን ጽንዓትን ዋጋ ኣለዎ ምዃኑ ዕምቆት ዘለዎ እምነት ። ጽባሕ ተኽእሎ ኣለዎ ። ናይ ሰብ ስሚዒት ዘይተሓፍሱ ናቱ ሃቡር ኣለዎ ። ተስፋ ዘይምቁራጽ — እቲ እምነት ህያው ምሕላው ።",
    hpC3L1: "ተስፋ ዕለት ዕለት ዝሕደስ ምርጫ እዩ",
    hpC3L2: "ሕልዎ — ተስፋ ምቁራጽ ሓደ ዕድል ሓደ ምርካቡ",
    hpC3L3: "ምስ ዝጥፍኡ ዘለዉ ሰባት ተስፋ ምምካፍ",
    hpC3L4: "ተስፋ ዝሕልዉ ሕብረተሰብ ኣይፈርስን",
    hpWhyTag: "ስለምንታይ ተስፋ ይቕጽል · ምኽንያቱ",
    hpWhyTitle: "ንምንታይ ተስፋ ምቁራጽ ክንኽልክሎ ኣለና",
    hpWhy1Title: "ናይ ኩሉ ተግባር ምንጪ እዩ",
    hpWhy1Text: "ዝኾነ ሰብ ብዘይ ተግባር ዋጋ ዘለዎ ምዃኑ ምኣምን ኣይሰርሕን ። ተስፋ ናይ ኩሉ ናይ ሰብ ጻዕሪ ሞተር — ኣወጊዱዎ ምቕስቃስ ምቁራጽ ። ተስፋ ምሕላው ዕድልካ ናይ ምቕያር ዓቕሚ ምሕላው ።",
    hpWhy2Title: "ሕብረተሰብ ይሕሉ",
    hpWhy2Text: "ሓደ ሰብ ተስፋ ምስ ዝቑርጽ — ኣብ ዙሪያኡ ዘለዉ ይስምዕዎ ። ሕብረተሰብ ሓቢሩ ተስፋ ምስ ዝቑርጽ ይፈርስ ። ኣብ ኣባላቱ — ብፍሉይ ኣብ ወጣሩ — ተስፋ ዝዕቅብ ሕብረተሰብ ዝጸንዕ ዝዓቢ ሕብረተሰብ እዩ ።",
    hpWhy3Title: "ጭንቀት ናብ ዕላማ ይቕይሮ",
    hpWhy3Text: "ኣብ ዘይተስፋ ዘለዎ ጭንቀት ናይ ሓቀኛ ሳቕ ። ኣብ ተስፋ ዘለዎ ጭንቀት ዛንታ ይኸውን — ፈተና — ምዕራፍ — ባህርይ ዝቐርጽ ሓይሊ ። ተስፋ ጻዕሪ ዓቅም ዓቅል ምዃኑ ። እዚ መወዳእታ ኣይኮነን ። ዝሓሸ ነገር ዝሰርሓሉ ####ዩ ።",
    hpWhy4Title: "ናብ ዝቕጽሉ ወለዶ ሓላፍነት እዩ",
    hpWhy4Text: "ተስፋ ዝሕልዉ ንርእሶም ጥራሕ ኣይኮኑን ። ጽንዓት ዘምስልዎ ዝኾነ ዓቢ ሰብ፡ ምቁራጽ ዝነፍጉ ዝኾነ ወላዲ፡ ምስ ወደቕ ዝቕስምሉ ዝኾነ ወጣር — ዝቕጽሉ ወለዶ ዘድልዮም ሓዊ ዝሕልዉ ።",
    hpAffirm: "ኣብ ዝኾነ ህሞት ኤድካ ዘይምሃብን ተስፋ ዘይምቁራጽን — ናትና ምርጫ፡ ናትና ሓይሊ ።",
    // Collective Growth
    sectionGrowth: "ኣብ ሓባራዊ ዕብየት ከነተኩር ይግበኣና",
    sectionGrowthDesc: "ሓባራዊ ዕብየት ብዙሕ ደስታን ሓጎስን ይፈጥረልና ፣ ውጽኢቱ'ውን ብቑልጡፍ እናተራእየ ዝመጽእ እዩ ። ስለዚ ናትና ዋና ዕላማ ክኸውን ይግባእ ።",
    growthDecl: "ኣብ ሓባራዊ ዕብየት ከነተኩር ይግበኣና — ብዙሕ ደስታን ሓጎስን ስለ ዝፈጥረልና ፣ ብቑልጡፍ እናተራእየ ዝመጽእ ውጽኢት ስለ ዘለዎ ። ስለዚ ነዚ ዝብል ዘለኩ ።",
    growthWhyTag: "ንምንታይ · ምኽንያት",
    growthWhyTitle: "ንምንታይ ሓባራዊ ዕብየት ኣገዳሲ እዩ",
    growthWhyIntro: "ናይ ሓባር ምዕባይ ካብ ናይ ውልቀ ጻዕሪ ዝሓይሽ ጥራሕ ኣይኮነን — ዝሃብተመ፡ ዝጠዓዓ፡ ዝነዊሐ ። እዞም ቀንዲ ምኽንያታት ።",
    growthWhy1Title: "ደስታን ሓጎስን ይፈጥር",
    growthWhy1Text: "ሓቢርካ ምዕባይ ናይ ውልቀ ዕወት ዘይፈጥሮ ስምዒት ይፈጥር — ኣብ ዙሪያኻ ዘለዉ ሰባት ምስ ዝዓቢ ናይ ሓቢርካ ሓጎስ ። ደስታ ኣብ ሕብረተሰብ ዝርኤ ዝቕዘን ።",
    growthWhy2Title: "ውጽኢቱ ብቑልጡፍ ይርኤ",
    growthWhy2Text: "ሰባት ክእለቶምን ጉዕዞኦምን ሃብቶምን ምስ ዘዋህልሉ፡ ፍጥነት ምዕባለ ብሓያሽ ይቀላጠፍ ። ሓደ ሰብ ብዓመታት ዝዕወቶ፡ ናይ ሓባር ጉጅለ ብኣዋርሕ ይዕወቶ ።",
    growthWhy3Title: "ዘለዓለም ሓይሊ ይሃንጽ",
    growthWhy3Text: "ሓቢርካ ዝዓበኻ ሕብረተሰብ ሱር ይሃንጽ — ናይ ሓባር ታሪኽ፡ ኣሳሰይ እምነት፡ ካብ ሓደ ውልቀ ሰብ ንላዕሊ ዝነብሩ ቅርጽታት ። እዚ ሓደ ወለዶ ናብ ዝቕጽሉ ዝሕልፎ ሓይሊ ።",
    growthWhatTag: "እንታይ ፍረ · ውጽኢታት",
    growthWhatTitle: "ፍረ ሓባራዊ ዕብየት ዝርኤ",
    growthWhatIntro: "እዞም ሓባራዊ ዕብየት ከምዝካይድ ዘርኡ ዝርኣዩ ምልክታት — ዝርኣ ዝስምዕ ዝስፈር ውጽኢታት ።",
    growthFruit1Title: "ጠቒዑ ዝጸንዕ ምትእስሳር",
    growthFruit1Text: "ሓቢርካ ዝሰርሑ ሰባት ዝሓሸ እምነት ይህሉ ። ናይ ሕብረተሰብ ፈትሊ ይሓይሽ፡ ምፍቅቃር ይወርድ፡ ምትሕብባር ናይ ሓፈሻ ልምዲ ይኸውን ።",
    growthFruit2Title: "ዝርኤ ናይ ሓባር ብልጽግና",
    growthFruit2Text: "ሃብትን ዕድልን ብዝሰፍሐ ይዝርጋሕ ። ብልጽግና ኣብ ሒደት ኢድ ኣይጸምቀን — ኣብ ኩሉ ሕብረተሰብ ዝርኤ ይኸውን ።",
    growthFruit3Title: "ናይ ሓባር ዕላማን ኣንፈትን",
    growthFruit3Text: "ሓቢርካ ምዕባይ ህዝቢ ኣብ ሓደ ዕላማ ይሰልፍ ። እዚ ናይ ሓባር ዕላማ ዕለታዊ ጻዕሪ ትርጉም ይህቦ ፣ ብሓዲኡ ናይ ምስራሕ ምዕርዐር ይእርም ።",
    growthFruit4Title: "ኣብ ጸቕጢ ጽንዓት",
    growthFruit4Text: "ሓቢርካ ዝዓበኻ ሕብረተሰብ ምህዞ — ናይ ቁጠባ ቅሉዕ፡ ጭንቀት፡ ናይ ደገ ጸቕጢ — ካብ ዝተነጸሉ ውልቀሰባት ዝሓሸ ይጻወሮ ።",
    growthHowTag: "ከመይ ንተግብሮ · ዋዕ",
    growthHowTitle: "ናብ ሓባራዊ ዕብየት ዝወስዱ ተግባራዊ ደረጃታት",
    growthHowIntro: "ሓባራዊ ዕብየት ብኣዘጋጃ ኣይካይድን — ስጕምቲ ብስጕምቲ ዝህነጽ ፣ ብቕሉዕ ምርጫታትን ዝቐጸሉ ልምድታትን ።",
    growthStep1Title: "ካብ \"ኣነ\" ናብ \"ንሕና\" ምቕያር",
    growthStep1Text: "ቀዳምን ቀንድን ስጕምቲ ናይ ሓሳብ ለውጢ ። ዝኾነ መደብ፡ ዝኾነ ፕሮጀክት፡ ዝኾነ ወሳኒ ብ\"ክረክብ ዝሓስብ\" ዘይኮነስ ብ\"እንታይ ንሃንጽ\" ምጅማር ። እዚ ናይ ሓሳብ ቅልያ ናይ ዘስዕቦ ኩሉ ሓይሊ ይቕይር ።",
    growthStep2Title: "ናይ ካልኦት ዓቕሚ ምሃብ",
    growthStep2Text: "ናቱ ሓባራዊ ዕብየት ካልኦት ናብ ዝዓቢ ምሕጋዝ ዝሓትት ። ፍልጠት ምካፍ፡ ማዕጶ ምኽፋት፡ ዝቕድምካ ካብኡ ዝሓሸ ምምሃር፡ ናይ ካልኦት ዕወት ብሰፊሑ ምቅላስ ። ናብ ካልኦት ዘፍሰስካዮ ተሸጕሮ ።",
    growthStep3Title: "ናይ ሓባር ፕሮጀክታት ምህናጽ",
    growthStep3Text: "ሓቢርካ ዝርኣ ነገራት ምፍጣር — ናይ ሕብረተሰብ ተበግሶ፡ ናይ ሓባር ሃብቲ፡ ምልክታት ዘለዎ ናይ ሓባር ዕላማ ። ናይ ሓባር ፕሮጀክታት ናይ ሓባር ኣካይዳ ሞተር ። ሰባት ዝርኣዮ ዝትንክፍዎ ቅርጺ ይህቡ ።",
    growthStep4Title: "ናይ ሓባር ዕወት ብሰፊሑ ምቅላስ",
    growthStep4Text: "ዝኾነ ናይ ሓባር ምዕራፍ ዝፈልጦ ምፍላጥ ይወሃቦ ። ሓቢርካ ምቅላስ ዕብየት ናይ ሓባር ምዃኑ ዘደልደሎ ። ናብ ሓደሽቲ ሰባትን ዝጠርጥሩን ሕብረተሰብ ዝዓቢ ምዃኑ — ምሳናን ብሓቢርን ርሒቦም ድዮም ።",
    growthAffirm: "ሓቢርና ንዓቢ — ብዙሕ ደስታን ሓጎስን ፣ ናብ ኩሉ ዝርኤ ብቑልጡፍ ዝመጽእ ውጽኢት ።",
    // Rest after Victory
    sectionRest: "ዓወት ምስ ተጎናጸፍና — ዕረፍቲ ይወሃቦ",
    sectionRestDesc: "ዓወት ናይ ዝተዓወትካ ሞሃ ጥራሕ ኣይኮነን — ካብ ናይ ሂወት ድኻም ዕረፍቲ ናይ ምርካብ መሰልካ ። ሕጂ ።",
    restDecl: "ዓወት ምስ ተጎናጸፍና — ሂወትና ካብ ላዕልን ታሕን ዘብል ድኻም ከነዕርፋ ።",
    restWhatTag: "ዓወት · ምርዳእ",
    restWhatTitle: "ሓቀኛ ዓወት ከመይ ይርኤ",
    restWhatIntro: "ዓወት ሓደ ፍጻሜ ጥራሕ ኣይኮነን — ናይ ዝቐጸለ ጻዕሪ፡ ምስዋእ፡ ጽንዓት ቅርሲ ። ዝረኸብናዮ ምርዳእ ዝወሃቦ ዕረፍቲ ኣቀባብላ ይቕይር ።",
    restPillar1Title: "ናይ ነዊሕ ቃልሲ መፈጸምታ",
    restPillar1Text: "ሓቀኛ ዓወት ናይ ጭንቀት ዝሓዘ ምዕራፍ ዝዓጹ — ዘይኽኣለ ዝነበረ ብጽንዓትን ዘይቋርጽ ጻዕርን ዝተረኽበ ።",
    restPillar2Title: "ሚዛን ዝተመለሰ",
    restPillar2Text: "ናይ ሂወት ቀጻሊ ላዕልን ታሕን ድካም ። ዓወት ሚዛን ዘምልስ — ካብ ናይ ዝቕጽሉ ወዳቕ ሻቕሎት ናጻ ዝኾነ ዝጸንዕ ምድሪ ።",
    restPillar3Title: "ብምርጫ ዝጅምር ሓድሽ ምዕራፍ",
    restPillar3Text: "ዝዓወትካ ምስ ዝስዕቦ ምዕራፍ ናትካ — ብናጽነት ዘይኮነስ ብምርጫን ሓጎስን ዝምራሕ ሂወት ።",
    restWhyTag: "ንምንታይ ዕረፍቲ · ኣገዳስነቱ",
    restWhyTitle: "ድሕሪ ዓወት ከምዘዕርፍ ዝሕቅቕ",
    restWhyIntro: "ዕረፍቲ ድኻም ኣይኮነን ስዕረት'ውን ኣይኮነን — ናይ ዕወት ልባዊ ምላሽ ። ድሕሪ ዓወት ዕረፍቲ ዘድሊ ምኽንያት ።",
    restWhy1Title: "ሰውነትን ሓሳብን ምሕዳስ ዘድሊ",
    restWhy1Text: "ዓወት ናብ ምምጻእ ዝተጠቀምካዮ ሓይሊ ናቱ ።  ዝኾነ ቃልሲ ናይ ሰውነትን ሓሳብን ዓቐን ይጥቐስ ። ዕረፍቲ ካብ ስንፍና ዝርሓቐ — ዝቕጽሉ ምዕራፍ ዝሃንጽ ምሕዳስ ።",
    restWhy2Title: "ጸጥታ ንጹር ሓሳብ ዘምጽእ",
    restWhy2Text: "ሂወት ቀጻሊ ቃልሲ ምስ ዝኸውን ብንጹር ምርኣይ ዓቕሚ ይቀንስ ። ዕረፍቲ ጸጥታ ዝፈጥር — ቀጻሊ ዝደሊ ዘይኮነስ ናትካ ዝቕጽሉ ዝሕቶ ።",
    restWhy3Title: "ዝተረኽበ ዓወት ምኽባር",
    restWhy3Text: "ብሕጡፍ ናብ ዝቕጽሉ ቃልሲ ምቅላስ ዝተረኽበ ዓወት ዘይምኽባር ። ንዕረፍቲ ምቑጻጽ ናይ ምስጋና ስጕምቲ — ሓቀኛ ዝሃነጸ ምኽናይ ። ምዕራፍ ብቕኑዕ ምዕጻው ።",
    restHowTag: "ከመይ ዕረፍቲ · ምትግባር",
    restHowTitle: "ናብ ዝፈርሕ ዕረፍቲ ዝወስዱ ተግባራዊ ደረጃታት",
    restHowIntro: "ዕረፍቲ ናቱ ልምዲ — ናይ ነዊሕ ጻዕሪ ምዕራፍ ምስ ዝስዕቦ ብቐጥታ ኣይምጽእን ። እዞም ደረጃታት ሓቀኛን ዘለዓለምን ዕረፍቲ ዘትርፉ ።",
    restStep1Title: "ዓወት ምዝራቡን ምቕባሉን",
    restStep1Text: "ዕረፍቲ ክጅምር ዓወት ብሓቂ ምቕባሉ ቅድሚ ኩሉ ። ብቓል ምዝርዙ፡ ምስ ካልኦት ምክፋሉ፡ ምቕባሉ ። ብዙሓት ናብ ሓደ ፍጻሜ ዘይጸናሑ ። ዘዕወትካዮ ስምሮ ። ሽዑ ጥራሕ ዕረፍቲ ካብ ሓቀኛ ፍጻሜ ይጅምር ።",
    restStep2Title: "ካብ ጻዕሪ ናጻ ዝኾነ ቦታ ምፍጣር",
    restStep2Text: "ዕረፍቲ ጻዕሪ ብቕሉዕ ምቁጻጽ ዝሓትት — ንዘሓ ዘይኮነስ ዝተወሰነ ሱሱ ። ናቱ ቦታ ምፍጣር: ናይ ጸጥታ ጊዜ፡ ዝቕምርር ናብርኻ፡ ዘምለስ ንጥፈታት ። ቀጻሊ ምምራሕ ልምዲ ካብዚ ምዕቃቡ ። ኩሉ ህሞት ምርዋዩ ኣየድልን ።",
    restStep3Title: "ናብ ሓጎሳት ምምላስ",
    restStep3Text: "ናይ ቃልሲ ዘመን ቀሊላት ሓጎሳት ይዘናጉ ። ዕረፍቲ ናብኦም ምምላስ ሰዓቱ — ዝምድናታት፡ ፈጠርነት፡ ፍጥረት፡ ሰሓቕ፡ ምስ ዝፈቱ ሰባት ዝብላዕ ። ናይ መጻኢ ሽልማት ኣይኮኑን — ሕጂ ዝርከቡ ናይ ሂወት ይዘት ።",
    restStep4Title: "ዝቕጽሉ ምዕራፍ ምሕዳስ — ዘይምቑዋሙ",
    restStep4Text: "ሓቀኛ ዕረፍቲ ወዲኡ ናይ ዝቕጽሉ ዕቤት ናብ ምቕዳሙ ዝደሊ ሓይሊ ምፍታሕ ። ዘይተሸጠ ጊዜ ምሃብ — ዝቕጽሉ ሕልሚ ካብ ዝዕረፈ ሓሳብ ብዝሓሸ ፍጥነትን ዕምቆትን ዝወጽእ — ዝደኸመ ሓሳብ ዝደፍኖ ኣይኮነን ። ናይ ጸጥታ ምስራሕ ምእማን ።",
    restAffirm: "ዓወት ምስ ተጎናጸፍና — ሂወትና ካብ ቃልሲ ድኻም ዕረፍቲ ትወሃቦ ። እዚ ዕረፍቲ ሕጂ ይጅምር ።",
  }
};

let currentLang = 'en';

function applyTranslation(lang) {
  const t = translations[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
  currentLang = lang;
}

document.querySelectorAll('.lang-btn').forEach(btn => {
  btn.addEventListener('click', () => applyTranslation(btn.getAttribute('data-lang')));
});

// ── Quotes Carousel ─────────────────────────────────────────────
const quotes = document.querySelectorAll('.quote-item');
const dots   = document.querySelectorAll('.dot');
let current  = 0;
let timer;

function showQuote(idx) {
  quotes.forEach((q, i) => q.classList.toggle('active', i === idx));
  dots.forEach((d, i)   => d.classList.toggle('active', i === idx));
  current = idx;
}

function nextQuote() { showQuote((current + 1) % quotes.length); }

function startCarousel() {
  timer = setInterval(nextQuote, 5000);
}

dots.forEach((dot, i) => {
  dot.addEventListener('click', () => { clearInterval(timer); showQuote(i); startCarousel(); });
});

showQuote(0);
startCarousel();

// ── Scroll Reveal ────────────────────────────────────────────────
const observer = new IntersectionObserver(
  entries => entries.forEach(e => {
    if (e.isIntersecting) {
      e.target.classList.add('visible');
      observer.unobserve(e.target);
    }
  }),
  { threshold: 0.12 }
);
document.querySelectorAll('.reveal').forEach(el => observer.observe(el));

// ── Smooth active nav link ────────────────────────────────────────
const sections = document.querySelectorAll('section[id]');
const navLinks  = document.querySelectorAll('.nav-links a');

const navObserver = new IntersectionObserver(
  entries => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        navLinks.forEach(a => a.classList.toggle('active-link', a.getAttribute('href') === `#${e.target.id}`));
      }
    });
  },
  { rootMargin: '-40% 0px -55% 0px' }
);
sections.forEach(s => navObserver.observe(s));

// ── Join form ────────────────────────────────────────────────────
const joinForm = document.getElementById('join-form');
if (joinForm) {
  const successMsg = document.getElementById('join-success');
  joinForm.addEventListener('submit', e => {
    e.preventDefault();
    const emailInput = joinForm.querySelector('.join-input');
    const email = emailInput.value.trim();
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (email && emailRegex.test(email)) {
      joinForm.style.display = 'none';
      if (successMsg) {
        successMsg.removeAttribute('hidden');
        successMsg.focus();
      }
    } else {
      emailInput.setCustomValidity('Please enter a valid email address.');
      emailInput.reportValidity();
      emailInput.setCustomValidity('');
    }
  });
}
