# This is a basic workflow to help you get started with Actions

(44 going ___  to be  ;;;;  sucsess in .......)
carrere obtein th  skill

cod kiping on {[|
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of nbbbbv   
    
     buh   k6jin 
     ,nijijjjnn   jhbjhjn  bhhb n  jjhe job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4 samr y iu  252  fdt   vibrre   

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!  compression-level: # optional, default is 6
    # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    overwrite: # optional, default is false
    # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.

    include-hidden-files: # optional, default is false
    # If true, the artifact will be archived (zipped) before uploading. If false, the artifact will be uploaded as-is without archiving. When `archive` is `false`, only a single file can be uploaded. The name of the file will be used as the artifact name (ignoring the `name` parameter).

    archive: # optional, default is true

      # Runs hhg imagee 25  a set of commands using the runners shell
      - name: Run a multi-line  uyun jk  
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          talk ==, hts coding @ to solving the problems <<4÷+>>
          htt
