
ኣብ መንጎ ገበናውን ሲቪላውን መስርሕ ዘሎ ፍልልይ፡ ብዝያዳ ቴክኒካውን ሕጋውን ኣገባብ፤

 1. ሕጋዊ ባህርን ዕላማን
ገበናዊ ኣገባብ፤
ምስ ገበናዊ ሕጊ ዝተኣሳሰር ጨንፈር ህዝባዊ ሕጊ ኮይኑ፡ ነቲ መንግስቲ ዘለዎ ናይ ምቕጻዕ መሰል (jus puniendi) ዘተግብር እዩ።

 ዕላማ፡ ምዕፋን ገበናት + ምክልኻል ህዝባዊ ስርዓት።

ሲቪላዊ ኣገባብ፤
ጨንፈር ናይ ብሕቲ ሕጊ ኮይኑ፡ ኣብ መንጎ ውልቀሰባት ዝፍጠር ዘይምርድዳእ ዝመርሕ እዩ።

 ዕላማ: ንዘጋጠመ ዘይምርድዳእ ንምፍታሕን ሕጋዊ ሚዛን (ካሕሳ) ንምምላስን እዩ።

 2. ስልጣን ፍርዲ
ገበነኛ፤
ህዝባዊ ምኽሳስ ናይ መንግስቲ ኮይኑ፡ ብዓቃቢ ሕጊ ህዝቢ ዝፍጸም እዩ።

 ግዳይ ተሓጋጋዚ ሲቪላዊ ክሲ ኣብ ቅድሚ ገበናዊ ቤት ፍርዲ ከቕርብ ይኽእል እዩ። ሲቪላዊ ሕጊ፤
ሕጋዊ ስጉምቲ ናይ ምቕራብ መሰል ናይ ውልቀ ውድባት እዩ (መትከል ውድባዊ ርእሰ-ምሕደራ)። ‎
3. መምርሒ መትከላት
 ኣብ ገበናዊ መስርሕ፤
መትከል ሕጋውነት ክሲ (ወይ ከከም ስርዓት ናይ ዓቃቢ ሕጊ ውሳነ)
መትከል ተጻባኢ መስርሕ
መትከል ናይ ንጽህና ግምት
መትከል ሕጋውነት ገበናትን መቕጻዕትን
ንጡፍ ተራ ዳኛ ኣብ ምምስራት ሓቂ (መብዛሕትኡ ግዜ መርማሪ ኣገባብ)
 ኣብ ሲቪላዊ መስርሕ፤
መትከል ርእሰ-ምሕደራ ውድባት (እቶም ወገናት ነቲ ፍርዲ ይመርሕዎ)
መትከል ተጻባኢ መስርሕ
መትከል ፍርዳዊ ገለልትነት
መትከል ህዝባዊ መስርሕ ፍርዲ (ብዘይካ)
ብመሰረቱ ተጻባኢ ኣገባብ እዩ።
‎
 4. ጾርን ሕግታት መርትዖን።
ገበነኛ፤
 ጾር መርትዖ ኣብ ዓቃቢ ሕጊ (ቤት ጽሕፈት ዓቃቢ ሕጊ) (ህዝባዊ)
 ልዑል ደረጃ መርትዖ: ኪኖ ምኽንያታዊ ጥርጣረ
 ናጽነት መርትዖ (ብዘይካ ኣብ ዝተወሰኑ ጉዳያት)
ሲቪል:
 ብመሰረት መትከል ዝተዓደለ ጾር መርትዖ: “actori incumbit probatio”
 ውሑድ ጽኑዕ ደረጃ መርትዖ (ብዝሒ ተኽእሎታት)
 መርትዖታት መብዛሕትኡ ግዜ ዝተገደቡ (ጽሑፋዊ ሰነዳት፡ ምስክርነት ወዘተ)

 5. መስርሕ መስርሕ
ገበነኛ፤
ምዕራፍ መርመራ (ፍርዳዊ ፖሊስ)
መባእታዊ መርመራ (ከከም ስርዓት)
ፍርዲ (ገበናዊ ቤት ፍርዲ)
ሲቪል:
ጻውዒት/ምሕሳብ
ንፍርዲ ምድላው
ናይ ፍርዲ መስርሕ
እቲ ውሳነ ምትግባር

 6. እንታይነት እገዳ
ገበነኛ፤

 መቕጻዕቲ (ማእሰርቲ፡ መቕጻዕቲ፡ ኣገልግሎት ማሕበረሰብ ወዘተ)
 ስጉምትታት ጸጥታ
ሲቪል:
 ምጽጋን (ጉድኣት)
 ምትግባር (ምምንዛዕ፣ ምግፋፍ ወዘተ)
ስርዝ ድልዝ ወይ ምስራዝ ተግባራት

 7. ረስ ጁዲካታ
ብመትከል ገበናዊ ውሳነ ኣብ ልዕሊ ሲቪላዊ ጉዳያት ስልጣን ኣለዎ (ገበናዊ ፍርዲ ኣብ ልዕሊ ሲቪላዊ ፍርዲ ይቕድም)፣ ብፍላይ ድማ ንህላወ ጭብጥታትን ገበነኛነትን ብዝምልከት።

8. ኣብ መንጎ ክልቲኦም ዝግበር ምትእስሳር
ተመሳሳሊ ኩነታት ድማ ንዝስዕቡ ክፈጥር ይኽእል እዩ፤
ገበናዊ መስርሕ (ንኣብነት ስርቂ)
ሲቪላዊ ክሲ (ንኣብነት፡ ካሕሳ ግዳይ)
 እቲ ግዳይ ክኸውን ዝኽእል፤
ፍሉይ ሲቪላዊ ክሲ ምቕራብ
ወይ ኣብ ገበናዊ መስርሕ ሲቪላዊ ውድብ ምዃን።

ብደረጃ ማስተርስ ዝካየድ ሲቪላዊ ኣገባብ፡ ኣብ ኣስተምህሮታት ወይ ምርምር ቀጥታዊ ኣጠቓቕማ ብትኽክል፡ ብሕጽር ዝበለን ዝተዋደደን ኣገባብ፤

1. ስልጣንን ብቕዓትን
ርእሰ-ጉዳይ ስልጣን ፍርዲ፡ ብባህሪ ናይቲ ክርክር ዝውሰን (ንኣብነት፡ ንግዳዊ ቤት ፍርዲ ንንግዳዊ ክርክር፡ ሲቪላዊ ቤት ፍርዲ ንብረታዊ ክርክር)።
ግዝኣታዊ ስልጣን (Teritorial jurisdiction)፦ ኣብ መንበሪ ገዛ ተኸሳሲ፣ ነቲ ክርክር ዝፈጠረሉ ቦታ፣ ወይ ድማ ኣቀማምጣ እቲ ዘካትዕ ንብረት መሰረት ብምግባር ብቑዕ ቤት ፍርዲ ይምስርት።
ስልጣን ርእሰ-ጉዳይ፦ ዝተወሰኑ ጉዳያት ንፍሉያት ኣብያተ ፍርዲ ዝተሓዝኡ እዮም (ንኣብነት፡ ጉዳያት ማሕበራዊ ድሕነት፡ ምምሕዳራዊ ክርክር)።
ሓፈሻዊ ሕጊ፡ ስልጣን ፍርዲ ብናይ ገዛእ ርእሱ ድሌት ወይ ከም መባእታዊ ተቓውሞ ክለዓል ኣለዎ።

2. ኣብቲ መስርሕ ዝሳተፉ ወገናት
ከሳሲ፡ ሕጋዊ ስጉምቲ ዘበገሰ ወገን።

ተኸሳሲ፡ እቲ ክሲ ዝቐርበሉ ወገን።

ጣልቃ ዝኣትዉ፡- ኣብቲ መስርሕ ክጽንበሩ ዝኽእሉ ሳልሳይ ወገን (ግዱድ ወይ ብወለንታ ምትእትታው)።

ምትኽኻእ ወገናት፡- ሓደ ውድብ ኣብ ዝሞተሉ እዋን፡ ውህደት ወይ ምምዳብ መሰላት ኣብ ዘጋጥመሉ እዋን ምትካእ ዝምልከት ሕግታት።

3. ኣገባባዊ ሰነዳት።
መስርሕ ምጅማር፡- ጻውዒት ወይ መመልከቲ፡ ከከም ዓይነት ኣገባብ።

ጥርዓናት፡- ነቲ ክስታትን ሕጋዊ ምጉታትን ዝገልጽ ጽሑፋዊ መግለጺታት።
ንጊዚያዊ ረድኤት ዝቐርብ ጻውዒት፡- ግዝያዊ ወይ ህጹጽ ውሳነ ንምርካብ የኽእል።

ኣገልግሎትን ምልክታን፡- ምስ መትከል ተጻባኢ መስርሕ ምኽባር የረጋግጽ።

4. ኣካይዳ ፍርዲ
መባእታዊ መርመራ፦ ምዕራፍ መርመራ መርትዖ፣ ምእካብ መርትዖን ምድላው ፋይል ጉዳይን።

ምስማዕ፡ ምግጣም ወገናትን ኣፋዊ ምቕራብ ክትዓትን።
ኣፋዊ ክትዕ፦ ነፍሲ ወከፍ ወገን ኣብ ቅድሚ ቤት ፍርዲ ዝቐርብ ኣፋዊ ክትዕ። ፍርዲ፡- ብዛዕባ መርትዖ ወይ ቅጥዒ ምኽንያታዊ ውሳነ፡ ይግባይ ክበሃል ይከኣል።

ምትግባር፡- ውሳነታት ቤት ፍርዲ ምትግባር (ምምንዛዕ፡ ክፍሊት መቕጻዕቲ፡ ብግዴታ ምፍጻም)።

5. ኣብ ሲቪላዊ መስርሕ መርትዖ
መትከል ናጽነት መርትዖ፦ ብሕጊ ካልእ እንተዘይተቐሚጡ ኩሉ መርትዖ ተቐባልነት ኣለዎ።

ጾር መርትዖ፦ ብመትከል ሕጋዊ ግምት ነዚ እንተዘይገልቢጡ ኣብ ከሳሲ እዩ ዝዓርፍ።

ኣገባብ መርትዖ፡ ጽሑፋዊ ሰነዳት፡ ምስክርነት፡ ግምታት፡ ርእይቶ ክኢላታት፡ ምቕባል።

ኤሌክትሮኒካዊ መርትዖ፦ ብመሰረት ሕግታት ተቐባልነትን ምርግጋፅን ተቐባልነት ዘለዎ እዩ።

6. መሰረታዊ መትከላት
መትከል ተጻባኢ መስርሕ፡ ነፍሲ ወከፍ ወገን ነቶም ተጻረርቲ ስነ-ሞጎታት ክፈልጦምን ክዛተየሎምን ኣለዎ።

መትከል ፍትሓውነት፡ ምኽልካል ናይ ምትላል ተግባራት።

መትከል ማዕርነት ኣጽዋር፡ ነፍሲ ወከፍ ወገን ጉዳዩ ዝከላኸለሉ ሓደ ዓይነት ኣገባብ ክህልዎ ኣለዎ።

መትከል ዕላዊነት፦ እቲ መስርሕ ፍርዲ ብዘይካ ኣብ ዝተወሰኑ ጉዳያት (ሓለዋ ትሕቲ ዕድመ ቆልዑ፣ ምስጢር መንግስቲ) ንህዝቢ ዝረአ እዩ።

7. መድሃኒታት
ይግባይ፡ ምሉእ ብምሉእ ነቲ ሓቅታትን ሕግን ብላዕለዋይ ቤት ፍርዲ ምግምጋም።
ይግባይ ናብ ቤት ፍርዲ ምኽሳስ፡ ዳግመ ግምት ስሩዕነት ናይቲ ኣገባብን ቅኑዕ ኣተገባብራ ሕግን።
ተቓውሞን ናይ ሳልሳይ ወገን ተቓውሞን፡- ብዘይሕጋዊ መንገዲ ንዝተዋህበ ፍርዲ ምቅዋም ወይ ንሳልሳይ ወገን ምጽላው።
ንኽግምገም መመልከቲ: ናይ መወዳእታ ውሳነ ብኸቢድ ጌጋ ወይ ምትላል እንተተበኪሉ ይከኣል እዩ።


////////_/_//////////////////%%/%%/%%/_



ስራሕካ መዓልታዊ እንታይ የጠቓልል?
ሓላፍነተይ ኣብ መንጎ ምምኽኻር ሕሙማትን ኣብ ደገን ይምቀል። ብዘይካ’ቲ ብብዙሕ ሞያታት ዝሰርሕ፡ ናይ ኒውሮሎጂ ጉዳይ ኣብ ዝጥርጠረሉ እዋን፡ ምስ ሕሙማት ንኒውሮሳይኮሎጂካዊ ገምጋም እራኸብ። ብድሕሪኡ ንርእይቶን ናይ ነዊሕ ግዜ ምክትታል ውጥን ንምትካልን እንደገና ይርእዮም። እዚ ምስ ናይ ደገ ሰብ ሞያ ምውህሃድን ጸብጻብ ምጽሓፍን እውን የጠቓልል።

💬 ንምንታይ ኢኻ ኒውሮሳይኮሎጂ መሪጽካ?
እቲ ዝያዳ ዘነቓቕሓኒ ጨንፈር ስነ-ልቦና እዩ። ኣብ ቅድሚት ዝስራዕ ሳይንሳዊ ምዕባለታት ኮይኑ፡ ኣብ ስነ-ልቦና እናወሰኸ ዝኸይድ ዘሎ ኮይኑ፡ ምስ ክሊኒካዊ ስነ-ልቦና ምትእስሳር እውን ይሕሉ፡ እዚ ድማ ልክዕ ከምኡ ኣገዳሲ ኮይኑ ይቕጽል!



@@@@#@@



ሕገ መንግስታዊ ሕጊ፣ ብንጹርን ዝተዋደደን ኣገባብ ዝቐርብ፤

1. ሕገ መንግስቲ
ንመንግስቲ ዝውድብ መሰረታዊ ጽሑፍ
ትካላትን ስልጣኖምን ይገልጽ
መሰልን ናጽነትን ዜጋታት የውሕስ

2. መንግስቲ
ካብ ዝቖመ ሕጋዊ ኣካል፤
ግዝኣት
በዝሒ ህዝቢ
ፖለቲካዊ ስልጣን
ቅጥዕታት መንግስቲ፤
ኣሃዳዊ መንግስቲ
ፌደራል ክልል ትግራይ

3. ልኡላውነት
ላዕለዋይ ስልጣን መንግስቲ
ናይዞም ክኾኑ ይኽእሉ፤
ህዝቢ (ህዝባዊ ልኡላውነት)
እቲ ህዝቢ (ሃገራዊ ልኡላውነት)

4. ምፍልላይ ስልጣን
ብሞንተስኪዮ ዝተዳለወ መትከል
ሓጋጊ ስልጣን: ሕግታት ይገብር
ፈጻሚ ስልጣን: ሕግታት የተግብር
ፍርዳዊ ስልጣን፡ ንክርክር ይፈርድ
ዕላማ፡ ምልኪ ንምክልኻልን ሚዛን ንምውሓስን እዩ።

5. ፖለቲካዊ ስርዓታት
ስርዓት ባይቶ፡ ምትሕብባር ኣብ መንጎ ፈጻምን ሓጋጊ ኣካልን ጨናፍር
ፕረዚደንታዊ ስርዓት፡ ጽኑዕ ምፍልላይ ስልጣን
ፍርቂ ፕረዚደንታዊ ስርዓት፡ ናይ ክልቲኦም ምትሕውዋስ እዩ።

6. ፖለቲካዊ ትካላት
መራሒ ሃገር (ፕረዚደንት ወይ ንጉስ)
መንግስቲ
ባይቶ (ሃገራዊ ባይቶ፡ ሰኔት)
ኣብያተ ፍርድን ቤት ፍርዲን

7. ልዕልና ሕጊ
መንግስቲ ኣብ ትሕቲ ሕጊ እዩ ዝግዛእ
ምኽባር ስርዓተ-መሰረት ስርዓታት
ምሕላው መሰረታዊ መሰላት

8. ሕገ መንግስታዊ ዳግመ ግምት
ሕግታት ምስ ሕገ መንግስቲ ዝሰማምዑ ምዃኖም የረጋግጽ
ብሕገ መንግስታዊ ቤት ፍርዲ ዝተረጋገፀ

9. መሰረታዊ መሰላትን ናጽነታትን
ሓሳብካ ናይ ምግላጽ ናጽነት
መሰል ህይወት
ናይ ምትእኽኻብ ናጽነት
መሰል ፍትሓዊ ፍርዲ

10. ሕገ መንግስታዊ ምኽልካል
ኣሰራርሓ ምምሕያሽ ሕገ መንግስቲ
መብዛሕትኡ ግዜ ንመጥቃዕቲ ንምክልኻል ዝምራሕ እዩ።








@#####




ብንጹርን ዝተዋደደን ኣገባብ ዝቐረበ ስነ-ገበን፤

1. ትርጉም ስነ-ገበን (criminology)
ስነ-ገበን ንገበን፡ ገበነኛ፡ ግዳይ፡ ከምኡ’ውን ገበን ንምምካት ዝሕግዙ ኣገባባት ዘጽንዕ ሳይንስ እዩ።

2. ገበን
ብሕጊ ዝተኸልከለን ብገበናዊ መቕጻዕቲ ዝቕጻዕን ተግባር።
ከምዚ ዝስዕብ ክምደብ ይኽእል፤
ፍራይም (ዕቱብ)
ወተሃደራዊ ገበን (ማእከላይ)
ምጥሓስ ሕጊ (ንእሽቶ) .

3. እቲ ገበነኛ
በደል ዝፍጽም ሰብ።
ብመሰረት ዝተፅንዐ፤
ስብእነቶም
ማሕበራዊ ሃዋህውኦም
ድርኺቶም

4. ጠንቂ ገበን
ውልቃዊ ረቛሒታት፡ ስነ-ኣእምሮኣዊ ጸገማት፡ ስብእና።
ማሕበራዊ ረቛሒታት፡ ድኽነት፡ ሽቕለት ኣልቦነት፡ ዘይማዕርነት
ረቛሒታት ስድራቤት፡ ትምህርቲ፡ ክትትል
ረቛሒታት ከባቢ፡ መነባብሮ ከባቢ፡ ከተማነት

5. ስነ-ገበናዊ ክልሰ-ሓሳባት
ክላሲካል ክልሰ-ሓሳብ፡ ናጻ ድሌት (ገበን ንምፍጻም ዝግበር ምርጫ)
ኣወንታዊ ክልሰ-ሓሳብ፡ ጽልዋ ስነ-ህይወታውን ማሕበራውን ረቛሒታት
ስነ-ማሕበረሰብኣዊ ክልሰ-ሓሳብ፡ ተራ ሕብረተሰብ ኣብ ገበን።

6. እቲ ግዳይ (ግዳይነት) .
መጽናዕቲ ግዳይ ገበን
ተራኦምን ተቓላዕነቶምን ዘጋጠሞም ሳዕቤናትን ይትንትን

7. እቲ ማሕበራዊ ምላሽ
ኩሉ እቲ ሕብረተሰብ ንገበን ዝህቦ ምላሽ፤
ፖሊስ
ፍትሒ
እስር ቤት
ማሕበራዊ ዳግመ ውህደት

8. ምክልኻል ገበን
ማሕበራዊ ምክልኻል፡ ትምህርቲ፡ ስራሕ
ኩነታዊ ምክልኻል፡ ጸጥታ፡ ምክትታል
ምክልኻል ገበን፡ ሕግታትን እገዳታትን

9. ምድግጋም ገበን ምግባር
ድሕሪ ምፍራድ ካልእ ገበን ናይ ምፍጻም ተግባር
ኣብ ስነ-ገበን ማእከላይ ጸገም

10. ገበናዊ ፖሊሲ
መንግስቲ ገበን ንምምካት ዘተግብሮ ስብስብ ስትራተጂታት።




ውሽጣዊ ህዝባዊ ሕጊ (ንጹርን ኣገዳስን)፤

1. ትርጉም ውሽጣዊ ህዝባዊ ሕጊ
ንሱ ድማ እቲ ዝመርሕ ኣካል ሕግታት እዩ፤
ኣሰራርሓ መንግስቲ ዝምልከት ምዃኑ’ዩ።
ኣብ መንጎ መንግስትን ዜጋታታን ዘሎ ዝምድናታት
ኣብ ውሽጢ ሓንቲ ሃገር ዝርከቡ መንግስታዊ ትካላት

2. ጨናፍር ውሽጣዊ ህዝባዊ ሕጊ
ቅዋማዊ ሕጊ፡ ውደባ ስልጣን (ፕረዚደንት፡ ባይቶ፡ መንግስቲ)
ምምሕዳራዊ ሕጊ፡ ኣሰራርሓ ህዝባዊ ምምሕዳር
ሕጊ ግብሪ፡ ምስ ግብሪ ዝተኣሳሰሩ ሕግታት
ሕጊ ምምሕዳር ከባቢ፡ ምሕደራ ኣውራጃታት፡ ኮሙናት ወዘተ።

3. መንግስቲ
ቅዋማት ባእታታት፤
ግዝኣት
በዝሒ ህዝቢ
ልኡላውነት (ልዑል ስልጣን ናይ ምውሳን)

4. ሕገ መንግስቲ
መሰረታዊ ሕጊ መንግስቲ
ህዝባዊ ስልጣን ይውድብ
መሰረታዊ መሰላት ዜጋታት የውሕስ

5. ምፍልላይ ስልጣን
ፈጻሚ ስልጣን: ሕግታት የተግብር
ሓጋጊ ስልጣን: ሕግታት የሕልፍ
ፍርዳዊ ስልጣን፡ ይፈርድን ይቐጽዕን

6. መትከል ሕጋውነት
እቲ ምምሕዳር ሕጊ ከኽብር ኣለዎ።
ዝኾነ ተግባር ልዕሊ ሕጊ ክኸውን ኣይክእልን እዩ።

7. ህዝባዊ ኣገልግሎት
ብመንግስቲ ዝቐርብ ሓፈሻዊ ረብሓ ዘለዎ ንጥፈት
መትከላት፤
ቀጻልነት
ማዕርነት
ምትዕጽጻፍ

8. ምምሕዳራዊ ተግባራት
ብምምሕዳር ዝውሰድ ውሳነታት
ክኸውን ይኽእል፤
ምቁጽጻር (ሓፈሻዊ) .
ውልቀ ሰብ





ሕጊ ግብሪ (ንጹርን ኣገደስትን ክዝከሩ ዘለዎም ነጥብታት)፤

1. ትርጉም ሕጊ ግብሪ
ሕጊ ግብሪ ንኹሎም ብመንግስትን ከባብያዊ ምምሕዳራትን ዝእከብ ግብሪ፣ ቀረፅን ኣበርክቶን ዝምልከቱ ሕግታት ዘጠቓለለ ጨንፈር ህዝባዊ ሕጊ እዩ።

2. ግብሪ
ግብሪ ማለት ዜጋታት ብዘይ ቀጥታዊ ካሕሳ ንመንግስቲ ክኸፍልዎ ዘለዎም ድምር ገንዘብ እዩ፣ ንመንግስታዊ ወጻኢታት ንምምዋል።

ኣብነታት፡ ቫት፡ ግብሪ ኣታዊ።

3. ምንጭታት ሕጊ ግብሪ
ሕጊ ግብሪ (ቀንዲ ምንጪ)
ሕገ መንግስቲ
ኣህጉራዊ ዋዕላታት
ሕጊ ፍርዲ
ምምሕዳራዊ ዶክትሪን።

4. መሰረታዊ መትከላት ግብሪ
መትከል ሕጋውነት፦ ሕጊ ጥራይ እዩ ግብሪ ዝፈጥር
መትከል ማዕርነት፦ ኩሎም ዜጋታት ኣብ ቅድሚ ሕጊ ማዕረ እዮም።
መትከል ኣድላይነት፦ ግብሪ ንረብሓ ህዝቢ የገልግል

5. ባእታታት ግብሪ
ከፋሊ ግብሪ፦ እቲ ግብሪ ዝኸፍል ሰብ
ግብሪ ዝኽፈል ንብረት፡- እንታይ እዩ ግብሪ ዝኽፈል (ኣታዊ፡ ሃልኪ ወዘተ)
መጠን ግብሪ፦ እቲ ዝትግበር ሚእታዊት
መሰረት ግብሪ፡- ግብሪ ንምሕሳብ ዝሕግዝ መሰረት

6. ዓይነታት ግብሪ
ቀጥታዊ ግብሪ፦ ብቐጥታ ብከፋሊ ግብሪ ዝኽፈል (ንኣብነት ግብሪ ኣታዊ)
ዘይቀጥታዊ ግብሪ፡ ኣብ ዋጋታት ዝተሓወሶ (ንኣብነት፡ ቫት)

7. ሜላታት ግብሪ
ምምላስ ግብሪ፦ ከፋሊ ግብሪ ኣታዊኦም ይገልጽ
ገምጋም፡ ስሌት ናይቲ ግብሪ
ምእካብ፡ ምኽፋል ግብሪ
ኦዲት ግብሪ፦ ብበዓል መዚ ግብሪ ምርግጋፅ

8. ምትላልን ምህዳምን ግብሪ
ምትላል ግብሪ (Tax Fraud)፦ ግብሪ ንኸይትኸፍል ዝግበር ዘይሕጋዊ ተግባር
ምህዳም ግብሪ፡- ኣብ ሕጊ ንዘሎ ነዃላት ምምዝማዝ ግብሪ ንምንካይ

9. መቕጻዕቲ ግብሪ
ዘይምኽባር ኣብ ዝፍጠረሉ እዋን፤
መቕጻዕቲ
መቕጻዕቲ
ሕጋዊ ክሲ

10. ምኽሳስ ግብሪ
ኩሉ ኣብ መንጎ ከፋሊ ግብሪን በዓል መዚ ግብሪን ዝፍጠር ዘይምርድዳእ (ጠለባት፣ ይግባይ ናብ ኣብያተ ፍርዲ)።






ቀዳምነት ክወሃቡ ዘለዎም ነገራት ፣  እቲ  ዘለኻዮ   ቦታ ናብ እትደልዮን ከዕውተካ  ዝኽእልን  ውሳነታት ከወስነክ ይኽእልዶ ኣድቂቅካ ምምርማር ። 

 

001_ ኣብ ትምህርቲ ዝተመርኮሰ ፣  ዘመናዊ  ሕርሻ  ወፍሪ  ንምግባር  መጾናዕቲ  ምሳድ፣ ብጉጅለን ብውህደትን ዝግበር                                                                                                      ወፍሪ  ምልምማድን ፣ምዝውታርን ።  

          ኣብ  ሳይነሳውን  ባህላውን ዝተሞርኮሰ  መጽናዕቲ  ብደቂቅ  ምሳድ ፣ 

002  መፍረ  እንስሳ ፣ ናብ  ምርግጋእ  ቁጠባዊ  ባይታ  ስለ  ዝፈጥር  ኣብ ወዳምነት ክስራዕን ክስራሓሉን ይግባእ ። 

